/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The AccountsIds model module.
 * @module model/AccountsIds
 * @version 0.7.15
 */
class AccountsIds {
    /**
     * Constructs a new <code>AccountsIds</code>.
     * @alias module:model/AccountsIds
     */
    constructor() { 
        
        AccountsIds.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>AccountsIds</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountsIds} obj Optional instance to populate.
     * @return {module:model/AccountsIds} The populated <code>AccountsIds</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountsIds();

            if (data.hasOwnProperty('publicKeys')) {
                obj['publicKeys'] = ApiClient.convertToType(data['publicKeys'], ['String']);
            }
            if (data.hasOwnProperty('addresses')) {
                obj['addresses'] = ApiClient.convertToType(data['addresses'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * The array of public keys.
 * @member {Array.<String>} publicKeys
 */
AccountsIds.prototype['publicKeys'] = undefined;

/**
 * The array of addresses.
 * @member {Array.<String>} addresses
 */
AccountsIds.prototype['addresses'] = undefined;






export default AccountsIds;

