/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountPropertyDTO from './AccountPropertyDTO';

/**
 * The AccountPropertiesDTO model module.
 * @module model/AccountPropertiesDTO
 * @version 0.7.15
 */
class AccountPropertiesDTO {
    /**
     * Constructs a new <code>AccountPropertiesDTO</code>.
     * @alias module:model/AccountPropertiesDTO
     * @param address {String} The address of the account in hexadecimal.
     * @param properties {Array.<module:model/AccountPropertyDTO>} 
     */
    constructor(address, properties) { 
        
        AccountPropertiesDTO.initialize(this, address, properties);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, address, properties) { 
        obj['address'] = address;
        obj['properties'] = properties;
    }

    /**
     * Constructs a <code>AccountPropertiesDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountPropertiesDTO} obj Optional instance to populate.
     * @return {module:model/AccountPropertiesDTO} The populated <code>AccountPropertiesDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountPropertiesDTO();

            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [AccountPropertyDTO]);
            }
        }
        return obj;
    }


}

/**
 * The address of the account in hexadecimal.
 * @member {String} address
 */
AccountPropertiesDTO.prototype['address'] = undefined;

/**
 * @member {Array.<module:model/AccountPropertyDTO>} properties
 */
AccountPropertiesDTO.prototype['properties'] = undefined;






export default AccountPropertiesDTO;

