/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import AccountPropertiesModificationTypeEnum from './AccountPropertiesModificationTypeEnum';





/**
* The AccountPropertiesModificationDTO model module.
* @module model/AccountPropertiesModificationDTO
* @version 0.7.15
*/
export default class AccountPropertiesModificationDTO {
    /**
    * Constructs a new <code>AccountPropertiesModificationDTO</code>.
    * @alias module:model/AccountPropertiesModificationDTO
    * @class
    * @param type {module:model/AccountPropertiesModificationTypeEnum} 
    * @param values {Array.<Object>} The address, transaction type or mosaic id to filter.
    */

    constructor(type, values) {
        



        this['type'] = type;this['values'] = values;

        
    }

    /**
    * Constructs a <code>AccountPropertiesModificationDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AccountPropertiesModificationDTO} obj Optional instance to populate.
    * @return {module:model/AccountPropertiesModificationDTO} The populated <code>AccountPropertiesModificationDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountPropertiesModificationDTO();

            
            
            

            if (data.hasOwnProperty('type')) {
                obj['type'] = AccountPropertiesModificationTypeEnum.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('values')) {
                obj['values'] = ApiClient.convertToType(data['values'], [Object]);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/AccountPropertiesModificationTypeEnum} type
    */
    type = undefined;
    /**
    * The address, transaction type or mosaic id to filter.
    * @member {Array.<Object>} values
    */
    values = undefined;








}


