/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountPropertiesModificationDTO from './AccountPropertiesModificationDTO';
import AccountPropertyTypeEnum from './AccountPropertyTypeEnum';

/**
 * The AccountPropertiesTransactionBodyDTO model module.
 * @module model/AccountPropertiesTransactionBodyDTO
 * @version 0.7.15
 */
class AccountPropertiesTransactionBodyDTO {
    /**
     * Constructs a new <code>AccountPropertiesTransactionBodyDTO</code>.
     * @alias module:model/AccountPropertiesTransactionBodyDTO
     * @param type {Object} 
     * @param modifications {Array.<module:model/AccountPropertiesModificationDTO>} 
     */
    constructor(type, modifications) { 
        
        AccountPropertiesTransactionBodyDTO.initialize(this, type, modifications);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, modifications) { 
        obj['type'] = type;
        obj['modifications'] = modifications;
    }

    /**
     * Constructs a <code>AccountPropertiesTransactionBodyDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountPropertiesTransactionBodyDTO} obj Optional instance to populate.
     * @return {module:model/AccountPropertiesTransactionBodyDTO} The populated <code>AccountPropertiesTransactionBodyDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountPropertiesTransactionBodyDTO();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('propertyType')) {
                obj['propertyType'] = AccountPropertyTypeEnum.constructFromObject(data['propertyType']);
            }
            if (data.hasOwnProperty('modifications')) {
                obj['modifications'] = ApiClient.convertToType(data['modifications'], [AccountPropertiesModificationDTO]);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} type
 */
AccountPropertiesTransactionBodyDTO.prototype['type'] = undefined;

/**
 * @member {module:model/AccountPropertyTypeEnum} propertyType
 */
AccountPropertiesTransactionBodyDTO.prototype['propertyType'] = undefined;

/**
 * @member {Array.<module:model/AccountPropertiesModificationDTO>} modifications
 */
AccountPropertiesTransactionBodyDTO.prototype['modifications'] = undefined;






export default AccountPropertiesTransactionBodyDTO;

