/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class AccountPropertyTypeEnum.
* @enum {}
* @readonly
*/
export default class AccountPropertyTypeEnum {
    
        /**
         * value: 1
         * @const
         */
        "1" = 1;

    
        /**
         * value: 2
         * @const
         */
        "2" = 2;

    
        /**
         * value: 4
         * @const
         */
        "4" = 4;

    
        /**
         * value: 5
         * @const
         */
        "5" = 5;

    
        /**
         * value: 129
         * @const
         */
        "129" = 129;

    
        /**
         * value: 130
         * @const
         */
        "130" = 130;

    
        /**
         * value: 132
         * @const
         */
        "132" = 132;

    

    /**
    * Returns a <code>AccountPropertyTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/AccountPropertyTypeEnum} The enum <code>AccountPropertyTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

