/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import LinkActionEnum from './LinkActionEnum';





/**
* The AccountLinkTransactionBodyDTO model module.
* @module model/AccountLinkTransactionBodyDTO
* @version 0.7.15
*/
export default class AccountLinkTransactionBodyDTO {
    /**
    * Constructs a new <code>AccountLinkTransactionBodyDTO</code>.
    * @alias module:model/AccountLinkTransactionBodyDTO
    * @class
    * @param remoteAccountKey {String} The public key of the remote account.
    * @param linkAction {module:model/LinkActionEnum} 
    */

    constructor(remoteAccountKey, linkAction) {
        



        this['remoteAccountKey'] = remoteAccountKey;this['linkAction'] = linkAction;

        
    }

    /**
    * Constructs a <code>AccountLinkTransactionBodyDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AccountLinkTransactionBodyDTO} obj Optional instance to populate.
    * @return {module:model/AccountLinkTransactionBodyDTO} The populated <code>AccountLinkTransactionBodyDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountLinkTransactionBodyDTO();

            
            
            

            if (data.hasOwnProperty('remoteAccountKey')) {
                obj['remoteAccountKey'] = ApiClient.convertToType(data['remoteAccountKey'], 'String');
            }
            if (data.hasOwnProperty('linkAction')) {
                obj['linkAction'] = LinkActionEnum.constructFromObject(data['linkAction']);
            }
        }
        return obj;
    }

    /**
    * The public key of the remote account.
    * @member {String} remoteAccountKey
    */
    remoteAccountKey = undefined;
    /**
    * @member {module:model/LinkActionEnum} linkAction
    */
    linkAction = undefined;








}


