/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountPropertiesModificationDTO from './AccountPropertiesModificationDTO';
import AccountPropertiesTransactionBodyDTO from './AccountPropertiesTransactionBodyDTO';
import AccountPropertyTypeEnum from './AccountPropertyTypeEnum';
import TransactionDTO from './TransactionDTO';

/**
 * The AccountPropertiesTransactionDTO model module.
 * @module model/AccountPropertiesTransactionDTO
 * @version 0.7.15
 */
class AccountPropertiesTransactionDTO {
    /**
     * Constructs a new <code>AccountPropertiesTransactionDTO</code>.
     * Transaction that prevents receiving transactions from undesired addresses, mosaics or sending certain transaction types.
     * @alias module:model/AccountPropertiesTransactionDTO
     * @implements module:model/TransactionDTO
     * @implements module:model/AccountPropertiesTransactionBodyDTO
     */
    constructor() { 
        TransactionDTO.initialize(this);AccountPropertiesTransactionBodyDTO.initialize(this, type, modifications);
        AccountPropertiesTransactionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['signature'] = signature;
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
        obj['max_fee'] = maxFee;
        obj['deadline'] = deadline;
        obj['modifications'] = modifications;
    }

    /**
     * Constructs a <code>AccountPropertiesTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountPropertiesTransactionDTO} obj Optional instance to populate.
     * @return {module:model/AccountPropertiesTransactionDTO} The populated <code>AccountPropertiesTransactionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountPropertiesTransactionDTO();
            TransactionDTO.constructFromObject(data, obj);
            AccountPropertiesTransactionBodyDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('max_fee')) {
                obj['max_fee'] = ApiClient.convertToType(data['max_fee'], ['Number']);
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
            if (data.hasOwnProperty('propertyType')) {
                obj['propertyType'] = AccountPropertyTypeEnum.constructFromObject(data['propertyType']);
            }
            if (data.hasOwnProperty('modifications')) {
                obj['modifications'] = ApiClient.convertToType(data['modifications'], [AccountPropertiesModificationDTO]);
            }
        }
        return obj;
    }


}

/**
 * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
 * @member {String} signature
 */
AccountPropertiesTransactionDTO.prototype['signature'] = undefined;

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
AccountPropertiesTransactionDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
AccountPropertiesTransactionDTO.prototype['version'] = undefined;

/**
 * @member {Object} type
 */
AccountPropertiesTransactionDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} max_fee
 */
AccountPropertiesTransactionDTO.prototype['max_fee'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
AccountPropertiesTransactionDTO.prototype['deadline'] = undefined;

/**
 * @member {module:model/AccountPropertyTypeEnum} propertyType
 */
AccountPropertiesTransactionDTO.prototype['propertyType'] = undefined;

/**
 * @member {Array.<module:model/AccountPropertiesModificationDTO>} modifications
 */
AccountPropertiesTransactionDTO.prototype['modifications'] = undefined;


// Implement TransactionDTO interface:
// Implement AccountPropertiesTransactionBodyDTO interface:
/**
 * @member {Object} type
 */
AccountPropertiesTransactionBodyDTO.prototype['type'] = undefined;
/**
 * @member {module:model/AccountPropertyTypeEnum} propertyType
 */
AccountPropertiesTransactionBodyDTO.prototype['propertyType'] = undefined;
/**
 * @member {Array.<module:model/AccountPropertiesModificationDTO>} modifications
 */
AccountPropertiesTransactionBodyDTO.prototype['modifications'] = undefined;




export default AccountPropertiesTransactionDTO;

