/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AccountLinkTransactionBodyDTO from './AccountLinkTransactionBodyDTO';
import LinkActionEnum from './LinkActionEnum';
import TransactionDTO from './TransactionDTO';

/**
 * The AccountLinkTransactionDTO model module.
 * @module model/AccountLinkTransactionDTO
 * @version 0.7.15
 */
class AccountLinkTransactionDTO {
    /**
     * Constructs a new <code>AccountLinkTransactionDTO</code>.
     * Delegates the account importance score to a proxy account.
     * @alias module:model/AccountLinkTransactionDTO
     * @implements module:model/TransactionDTO
     * @implements module:model/AccountLinkTransactionBodyDTO
     */
    constructor() { 
        TransactionDTO.initialize(this);AccountLinkTransactionBodyDTO.initialize(this, remoteAccountKey, linkAction);
        AccountLinkTransactionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['signature'] = signature;
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
        obj['max_fee'] = maxFee;
        obj['deadline'] = deadline;
        obj['remoteAccountKey'] = remoteAccountKey;
        obj['linkAction'] = linkAction;
    }

    /**
     * Constructs a <code>AccountLinkTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AccountLinkTransactionDTO} obj Optional instance to populate.
     * @return {module:model/AccountLinkTransactionDTO} The populated <code>AccountLinkTransactionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountLinkTransactionDTO();
            TransactionDTO.constructFromObject(data, obj);
            AccountLinkTransactionBodyDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('max_fee')) {
                obj['max_fee'] = ApiClient.convertToType(data['max_fee'], ['Number']);
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
            if (data.hasOwnProperty('remoteAccountKey')) {
                obj['remoteAccountKey'] = ApiClient.convertToType(data['remoteAccountKey'], 'String');
            }
            if (data.hasOwnProperty('linkAction')) {
                obj['linkAction'] = LinkActionEnum.constructFromObject(data['linkAction']);
            }
        }
        return obj;
    }


}

/**
 * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
 * @member {String} signature
 */
AccountLinkTransactionDTO.prototype['signature'] = undefined;

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
AccountLinkTransactionDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
AccountLinkTransactionDTO.prototype['version'] = undefined;

/**
 * @member {Object} type
 */
AccountLinkTransactionDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} max_fee
 */
AccountLinkTransactionDTO.prototype['max_fee'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
AccountLinkTransactionDTO.prototype['deadline'] = undefined;

/**
 * The public key of the remote account.
 * @member {String} remoteAccountKey
 */
AccountLinkTransactionDTO.prototype['remoteAccountKey'] = undefined;

/**
 * @member {module:model/LinkActionEnum} linkAction
 */
AccountLinkTransactionDTO.prototype['linkAction'] = undefined;


// Implement TransactionDTO interface:
// Implement AccountLinkTransactionBodyDTO interface:
/**
 * @member {Object} type
 */
AccountLinkTransactionBodyDTO.prototype['type'] = undefined;
/**
 * The public key of the remote account.
 * @member {String} remoteAccountKey
 */
AccountLinkTransactionBodyDTO.prototype['remoteAccountKey'] = undefined;
/**
 * @member {module:model/LinkActionEnum} linkAction
 */
AccountLinkTransactionBodyDTO.prototype['linkAction'] = undefined;




export default AccountLinkTransactionDTO;

