/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import AccountPropertiesModificationDTO from './AccountPropertiesModificationDTO';
import AccountPropertiesTransactionBodyDTO from './AccountPropertiesTransactionBodyDTO';
import AccountPropertyTypeEnum from './AccountPropertyTypeEnum';
import EntityTypeEnum from './EntityTypeEnum';
import NetworkTypeEnum from './NetworkTypeEnum';
import TransactionDTO from './TransactionDTO';
import UInt64DTO from './UInt64DTO';





/**
* The AccountPropertiesTransactionDTO model module.
* @module model/AccountPropertiesTransactionDTO
* @version 0.7.15
*/
export default class AccountPropertiesTransactionDTO {
    /**
    * Constructs a new <code>AccountPropertiesTransactionDTO</code>.
    * Transaction that prevents receiving transactions from undesired addresses, mosaics or sending certain transaction types.
    * @alias module:model/AccountPropertiesTransactionDTO
    * @class
    * @implements module:model/TransactionDTO
    * @implements module:model/AccountPropertiesTransactionBodyDTO
    * @param signature {String} The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    * @param signer {String} The public key of the entity signer formatted as hexadecimal.
    * @param version {module:model/NetworkTypeEnum} 
    * @param type {module:model/EntityTypeEnum} 
    * @param maxFee {module:model/UInt64DTO} 
    * @param deadline {module:model/UInt64DTO} 
    * @param propertyType {module:model/AccountPropertyTypeEnum} 
    * @param modifications {Array.<module:model/AccountPropertiesModificationDTO>} 
    */

    constructor(signature, signer, version, type, maxFee, deadline, propertyType, modifications) {
        



        

        
    }

    /**
    * Constructs a <code>AccountPropertiesTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AccountPropertiesTransactionDTO} obj Optional instance to populate.
    * @return {module:model/AccountPropertiesTransactionDTO} The populated <code>AccountPropertiesTransactionDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AccountPropertiesTransactionDTO();

            
            
            TransactionDTO.constructFromObject(data, obj);AccountPropertiesTransactionBodyDTO.constructFromObject(data, obj);

        }
        return obj;
    }



    // Implement TransactionDTO interface:
    /**
    * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    * @member {String} signature
    */
    signature = undefined;
/**
    * The public key of the entity signer formatted as hexadecimal.
    * @member {String} signer
    */
    signer = undefined;
/**
    * @member {module:model/NetworkTypeEnum} version
    */
    version = undefined;
/**
    * @member {module:model/EntityTypeEnum} type
    */
    type = undefined;
/**
    * @member {module:model/UInt64DTO} max_fee
    */
    max_fee = undefined;
/**
    * @member {module:model/UInt64DTO} deadline
    */
    deadline = undefined;

    // Implement AccountPropertiesTransactionBodyDTO interface:
    /**
    * @member {module:model/AccountPropertyTypeEnum} propertyType
    */
    propertyType = undefined;
/**
    * @member {Array.<module:model/AccountPropertiesModificationDTO>} modifications
    */
    modifications = undefined;







}


