/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import AddressAliasTransactionBodyDTO from './AddressAliasTransactionBodyDTO';
import AliasActionEnum from './AliasActionEnum';
import EntityTypeEnum from './EntityTypeEnum';
import NetworkTypeEnum from './NetworkTypeEnum';
import TransactionDTO from './TransactionDTO';
import UInt64DTO from './UInt64DTO';





/**
* The AddressAliasTransactionDTO model module.
* @module model/AddressAliasTransactionDTO
* @version 0.7.15
*/
export default class AddressAliasTransactionDTO {
    /**
    * Constructs a new <code>AddressAliasTransactionDTO</code>.
    * Transaction that attaches a namespace to an account.
    * @alias module:model/AddressAliasTransactionDTO
    * @class
    * @implements module:model/TransactionDTO
    * @implements module:model/AddressAliasTransactionBodyDTO
    * @param signature {String} The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    * @param signer {String} The public key of the entity signer formatted as hexadecimal.
    * @param version {module:model/NetworkTypeEnum} 
    * @param type {module:model/EntityTypeEnum} 
    * @param maxFee {module:model/UInt64DTO} 
    * @param deadline {module:model/UInt64DTO} 
    * @param aliasAction {module:model/AliasActionEnum} 
    * @param namespaceId {module:model/UInt64DTO} 
    * @param address {String} The aliased address in hexadecimal.
    */

    constructor(signature, signer, version, type, maxFee, deadline, aliasAction, namespaceId, address) {
        



        

        
    }

    /**
    * Constructs a <code>AddressAliasTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AddressAliasTransactionDTO} obj Optional instance to populate.
    * @return {module:model/AddressAliasTransactionDTO} The populated <code>AddressAliasTransactionDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddressAliasTransactionDTO();

            
            
            TransactionDTO.constructFromObject(data, obj);AddressAliasTransactionBodyDTO.constructFromObject(data, obj);

        }
        return obj;
    }



    // Implement TransactionDTO interface:
    /**
    * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    * @member {String} signature
    */
    signature = undefined;
/**
    * The public key of the entity signer formatted as hexadecimal.
    * @member {String} signer
    */
    signer = undefined;
/**
    * @member {module:model/NetworkTypeEnum} version
    */
    version = undefined;
/**
    * @member {module:model/EntityTypeEnum} type
    */
    type = undefined;
/**
    * @member {module:model/UInt64DTO} max_fee
    */
    max_fee = undefined;
/**
    * @member {module:model/UInt64DTO} deadline
    */
    deadline = undefined;

    // Implement AddressAliasTransactionBodyDTO interface:
    /**
    * @member {module:model/AliasActionEnum} aliasAction
    */
    aliasAction = undefined;
/**
    * @member {module:model/UInt64DTO} namespaceId
    */
    namespaceId = undefined;
/**
    * The aliased address in hexadecimal.
    * @member {String} address
    */
    address = undefined;







}


