/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AliasActionEnum from './AliasActionEnum';

/**
 * The AddressAliasTransactionBodyDTO model module.
 * @module model/AddressAliasTransactionBodyDTO
 * @version 0.7.15
 */
class AddressAliasTransactionBodyDTO {
    /**
     * Constructs a new <code>AddressAliasTransactionBodyDTO</code>.
     * @alias module:model/AddressAliasTransactionBodyDTO
     * @param aliasAction {module:model/AliasActionEnum} 
     * @param namespaceId {Array.<Number>} 
     * @param address {String} The aliased address in hexadecimal.
     */
    constructor(aliasAction, namespaceId, address) { 
        
        AddressAliasTransactionBodyDTO.initialize(this, aliasAction, namespaceId, address);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, aliasAction, namespaceId, address) { 
        obj['aliasAction'] = aliasAction;
        obj['namespaceId'] = namespaceId;
        obj['address'] = address;
    }

    /**
     * Constructs a <code>AddressAliasTransactionBodyDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AddressAliasTransactionBodyDTO} obj Optional instance to populate.
     * @return {module:model/AddressAliasTransactionBodyDTO} The populated <code>AddressAliasTransactionBodyDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AddressAliasTransactionBodyDTO();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('aliasAction')) {
                obj['aliasAction'] = AliasActionEnum.constructFromObject(data['aliasAction']);
            }
            if (data.hasOwnProperty('namespaceId')) {
                obj['namespaceId'] = ApiClient.convertToType(data['namespaceId'], ['Number']);
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object} type
 */
AddressAliasTransactionBodyDTO.prototype['type'] = undefined;

/**
 * @member {module:model/AliasActionEnum} aliasAction
 */
AddressAliasTransactionBodyDTO.prototype['aliasAction'] = undefined;

/**
 * @member {Array.<Number>} namespaceId
 */
AddressAliasTransactionBodyDTO.prototype['namespaceId'] = undefined;

/**
 * The aliased address in hexadecimal.
 * @member {String} address
 */
AddressAliasTransactionBodyDTO.prototype['address'] = undefined;






export default AddressAliasTransactionBodyDTO;

