/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import CosignatureDTO from './CosignatureDTO';





/**
* The AggregateTransactionBodyDTO model module.
* @module model/AggregateTransactionBodyDTO
* @version 0.7.15
*/
export default class AggregateTransactionBodyDTO {
    /**
    * Constructs a new <code>AggregateTransactionBodyDTO</code>.
    * @alias module:model/AggregateTransactionBodyDTO
    * @class
    * @param cosignatures {Array.<module:model/CosignatureDTO>} An array of transaction cosignatures.
    * @param transactions {Array.<Object>} The array of transactions initiated by different accounts.
    */

    constructor(cosignatures, transactions) {
        



        this['cosignatures'] = cosignatures;this['transactions'] = transactions;

        
    }

    /**
    * Constructs a <code>AggregateTransactionBodyDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AggregateTransactionBodyDTO} obj Optional instance to populate.
    * @return {module:model/AggregateTransactionBodyDTO} The populated <code>AggregateTransactionBodyDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AggregateTransactionBodyDTO();

            
            
            

            if (data.hasOwnProperty('cosignatures')) {
                obj['cosignatures'] = ApiClient.convertToType(data['cosignatures'], [CosignatureDTO]);
            }
            if (data.hasOwnProperty('transactions')) {
                obj['transactions'] = ApiClient.convertToType(data['transactions'], [Object]);
            }
        }
        return obj;
    }

    /**
    * An array of transaction cosignatures.
    * @member {Array.<module:model/CosignatureDTO>} cosignatures
    */
    cosignatures = undefined;
    /**
    * The array of transactions initiated by different accounts.
    * @member {Array.<Object>} transactions
    */
    transactions = undefined;








}


