/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AggregateTransactionBodyDTO from './AggregateTransactionBodyDTO';
import CosignatureDTO from './CosignatureDTO';
import EmbeddedTransactionInfoDTO from './EmbeddedTransactionInfoDTO';
import TransactionDTO from './TransactionDTO';

/**
 * The AggregateTransactionDTO model module.
 * @module model/AggregateTransactionDTO
 * @version 0.7.15
 */
class AggregateTransactionDTO {
    /**
     * Constructs a new <code>AggregateTransactionDTO</code>.
     * Transaction that combines multiple transactions together.
     * @alias module:model/AggregateTransactionDTO
     * @implements module:model/TransactionDTO
     * @implements module:model/AggregateTransactionBodyDTO
     */
    constructor() { 
        TransactionDTO.initialize(this);AggregateTransactionBodyDTO.initialize(this, cosignatures, transactions);
        AggregateTransactionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['signature'] = signature;
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
        obj['max_fee'] = maxFee;
        obj['deadline'] = deadline;
        obj['cosignatures'] = cosignatures;
        obj['transactions'] = transactions;
    }

    /**
     * Constructs a <code>AggregateTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/AggregateTransactionDTO} obj Optional instance to populate.
     * @return {module:model/AggregateTransactionDTO} The populated <code>AggregateTransactionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AggregateTransactionDTO();
            TransactionDTO.constructFromObject(data, obj);
            AggregateTransactionBodyDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('max_fee')) {
                obj['max_fee'] = ApiClient.convertToType(data['max_fee'], ['Number']);
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
            if (data.hasOwnProperty('cosignatures')) {
                obj['cosignatures'] = ApiClient.convertToType(data['cosignatures'], [CosignatureDTO]);
            }
            if (data.hasOwnProperty('transactions')) {
                obj['transactions'] = ApiClient.convertToType(data['transactions'], [EmbeddedTransactionInfoDTO]);
            }
        }
        return obj;
    }


}

/**
 * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
 * @member {String} signature
 */
AggregateTransactionDTO.prototype['signature'] = undefined;

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
AggregateTransactionDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
AggregateTransactionDTO.prototype['version'] = undefined;

/**
 * @member {Object} type
 */
AggregateTransactionDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} max_fee
 */
AggregateTransactionDTO.prototype['max_fee'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
AggregateTransactionDTO.prototype['deadline'] = undefined;

/**
 * An array of transaction cosignatures.
 * @member {Array.<module:model/CosignatureDTO>} cosignatures
 */
AggregateTransactionDTO.prototype['cosignatures'] = undefined;

/**
 * The array of transactions initiated by different accounts.
 * @member {Array.<module:model/EmbeddedTransactionInfoDTO>} transactions
 */
AggregateTransactionDTO.prototype['transactions'] = undefined;


// Implement TransactionDTO interface:
// Implement AggregateTransactionBodyDTO interface:
/**
 * @member {Object} type
 */
AggregateTransactionBodyDTO.prototype['type'] = undefined;
/**
 * An array of transaction cosignatures.
 * @member {Array.<module:model/CosignatureDTO>} cosignatures
 */
AggregateTransactionBodyDTO.prototype['cosignatures'] = undefined;
/**
 * The array of transactions initiated by different accounts.
 * @member {Array.<module:model/EmbeddedTransactionInfoDTO>} transactions
 */
AggregateTransactionBodyDTO.prototype['transactions'] = undefined;




export default AggregateTransactionDTO;

