/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The AliasActionEnum model module.
* @module model/AliasActionEnum
* @version 0.7.15
*/
export default class AliasActionEnum {
    /**
    * Constructs a new <code>AliasActionEnum</code>.
    * The alias action: * 0 -  Link alias. * 1 -  Unlink alias. 
    * @alias module:model/AliasActionEnum
    * @class
    */

    constructor() {
        



        

        
    }

    /**
    * Constructs a <code>AliasActionEnum</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/AliasActionEnum} obj Optional instance to populate.
    * @return {module:model/AliasActionEnum} The populated <code>AliasActionEnum</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new AliasActionEnum();

            
            
            

        }
        return obj;
    }









}


