/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ArtifactExpiryReceiptDTOAllOf from './ArtifactExpiryReceiptDTOAllOf';
import ReceiptDTO from './ReceiptDTO';

/**
 * The ArtifactExpiryReceiptDTO model module.
 * @module model/ArtifactExpiryReceiptDTO
 * @version 0.7.15
 */
class ArtifactExpiryReceiptDTO {
    /**
     * Constructs a new <code>ArtifactExpiryReceiptDTO</code>.
     * An artifact namespace or mosaic expired.
     * @alias module:model/ArtifactExpiryReceiptDTO
     * @implements module:model/ReceiptDTO
     * @implements module:model/ArtifactExpiryReceiptDTOAllOf
     */
    constructor() { 
        ReceiptDTO.initialize(this, version, type);ArtifactExpiryReceiptDTOAllOf.initialize(this, artifactId);
        ArtifactExpiryReceiptDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['version'] = version;
        obj['type'] = type;
        obj['artifactId'] = artifactId;
    }

    /**
     * Constructs a <code>ArtifactExpiryReceiptDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ArtifactExpiryReceiptDTO} obj Optional instance to populate.
     * @return {module:model/ArtifactExpiryReceiptDTO} The populated <code>ArtifactExpiryReceiptDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ArtifactExpiryReceiptDTO();
            ReceiptDTO.constructFromObject(data, obj);
            ArtifactExpiryReceiptDTOAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ReceiptDTO.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('artifactId')) {
                obj['artifactId'] = ApiClient.convertToType(data['artifactId'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * The version of the receipt.
 * @member {Number} version
 */
ArtifactExpiryReceiptDTO.prototype['version'] = undefined;

/**
 * @member {module:model/ReceiptDTO} type
 */
ArtifactExpiryReceiptDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} artifactId
 */
ArtifactExpiryReceiptDTO.prototype['artifactId'] = undefined;


// Implement ReceiptDTO interface:
/**
 * The version of the receipt.
 * @member {Number} version
 */
ReceiptDTO.prototype['version'] = undefined;
/**
 * @member {module:model/ReceiptDTO} type
 */
ReceiptDTO.prototype['type'] = undefined;
// Implement ArtifactExpiryReceiptDTOAllOf interface:
/**
 * @member {Array.<Number>} artifactId
 */
ArtifactExpiryReceiptDTOAllOf.prototype['artifactId'] = undefined;




export default ArtifactExpiryReceiptDTO;

