/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BalanceTransferReceiptDTOAllOf model module.
 * @module model/BalanceTransferReceiptDTOAllOf
 * @version 0.7.15
 */
class BalanceTransferReceiptDTOAllOf {
    /**
     * Constructs a new <code>BalanceTransferReceiptDTOAllOf</code>.
     * @alias module:model/BalanceTransferReceiptDTOAllOf
     * @param sender {String} The public key of the sender.
     * @param recipient {String} The public key of the recipient.
     * @param mosaicId {Array.<Number>} 
     * @param amount {Array.<Number>} 
     */
    constructor(sender, recipient, mosaicId, amount) { 
        
        BalanceTransferReceiptDTOAllOf.initialize(this, sender, recipient, mosaicId, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, sender, recipient, mosaicId, amount) { 
        obj['sender'] = sender;
        obj['recipient'] = recipient;
        obj['mosaicId'] = mosaicId;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>BalanceTransferReceiptDTOAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BalanceTransferReceiptDTOAllOf} obj Optional instance to populate.
     * @return {module:model/BalanceTransferReceiptDTOAllOf} The populated <code>BalanceTransferReceiptDTOAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BalanceTransferReceiptDTOAllOf();

            if (data.hasOwnProperty('sender')) {
                obj['sender'] = ApiClient.convertToType(data['sender'], 'String');
            }
            if (data.hasOwnProperty('recipient')) {
                obj['recipient'] = ApiClient.convertToType(data['recipient'], 'String');
            }
            if (data.hasOwnProperty('mosaicId')) {
                obj['mosaicId'] = ApiClient.convertToType(data['mosaicId'], ['Number']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * The public key of the sender.
 * @member {String} sender
 */
BalanceTransferReceiptDTOAllOf.prototype['sender'] = undefined;

/**
 * The public key of the recipient.
 * @member {String} recipient
 */
BalanceTransferReceiptDTOAllOf.prototype['recipient'] = undefined;

/**
 * @member {Array.<Number>} mosaicId
 */
BalanceTransferReceiptDTOAllOf.prototype['mosaicId'] = undefined;

/**
 * @member {Array.<Number>} amount
 */
BalanceTransferReceiptDTOAllOf.prototype['amount'] = undefined;






export default BalanceTransferReceiptDTOAllOf;

