/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import BalanceChangeReceiptDTOAllOf from './BalanceChangeReceiptDTOAllOf';
import ReceiptDTO from './ReceiptDTO';

/**
 * The BalanceChangeReceiptDTO model module.
 * @module model/BalanceChangeReceiptDTO
 * @version 0.7.15
 */
class BalanceChangeReceiptDTO {
    /**
     * Constructs a new <code>BalanceChangeReceiptDTO</code>.
     * The invisible state change changed an account balance.
     * @alias module:model/BalanceChangeReceiptDTO
     * @implements module:model/ReceiptDTO
     * @implements module:model/BalanceChangeReceiptDTOAllOf
     */
    constructor() { 
        ReceiptDTO.initialize(this, version, type);BalanceChangeReceiptDTOAllOf.initialize(this, account, mosaicId, amount);
        BalanceChangeReceiptDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['version'] = version;
        obj['type'] = type;
        obj['account'] = account;
        obj['mosaicId'] = mosaicId;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>BalanceChangeReceiptDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BalanceChangeReceiptDTO} obj Optional instance to populate.
     * @return {module:model/BalanceChangeReceiptDTO} The populated <code>BalanceChangeReceiptDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BalanceChangeReceiptDTO();
            ReceiptDTO.constructFromObject(data, obj);
            BalanceChangeReceiptDTOAllOf.constructFromObject(data, obj);

            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ReceiptDTO.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('account')) {
                obj['account'] = ApiClient.convertToType(data['account'], 'String');
            }
            if (data.hasOwnProperty('mosaicId')) {
                obj['mosaicId'] = ApiClient.convertToType(data['mosaicId'], ['Number']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * The version of the receipt.
 * @member {Number} version
 */
BalanceChangeReceiptDTO.prototype['version'] = undefined;

/**
 * @member {module:model/ReceiptDTO} type
 */
BalanceChangeReceiptDTO.prototype['type'] = undefined;

/**
 * The target account public key.
 * @member {String} account
 */
BalanceChangeReceiptDTO.prototype['account'] = undefined;

/**
 * @member {Array.<Number>} mosaicId
 */
BalanceChangeReceiptDTO.prototype['mosaicId'] = undefined;

/**
 * @member {Array.<Number>} amount
 */
BalanceChangeReceiptDTO.prototype['amount'] = undefined;


// Implement ReceiptDTO interface:
/**
 * The version of the receipt.
 * @member {Number} version
 */
ReceiptDTO.prototype['version'] = undefined;
/**
 * @member {module:model/ReceiptDTO} type
 */
ReceiptDTO.prototype['type'] = undefined;
// Implement BalanceChangeReceiptDTOAllOf interface:
/**
 * The target account public key.
 * @member {String} account
 */
BalanceChangeReceiptDTOAllOf.prototype['account'] = undefined;
/**
 * @member {Array.<Number>} mosaicId
 */
BalanceChangeReceiptDTOAllOf.prototype['mosaicId'] = undefined;
/**
 * @member {Array.<Number>} amount
 */
BalanceChangeReceiptDTOAllOf.prototype['amount'] = undefined;




export default BalanceChangeReceiptDTO;

