/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BlockDTOAllOf model module.
 * @module model/BlockDTOAllOf
 * @version 0.7.15
 */
class BlockDTOAllOf {
    /**
     * Constructs a new <code>BlockDTOAllOf</code>.
     * @alias module:model/BlockDTOAllOf
     * @param height {Array.<Number>} 
     * @param timestamp {Array.<Number>} 
     * @param difficulty {Array.<Number>} 
     * @param feeMultiplier {Number} The fee multiplier applied to transactions contained in block.
     * @param previousBlockHash {String} The hash of the previous block.
     * @param blockTransactionsHash {String} The transactions included in a block are hashed forming a merkle tree. The root of the tree summarizes them. 
     * @param blockReceiptsHash {String} The collection of receipts  are hashed into a merkle tree and linked to a block. The block header stores the root hash. 
     * @param stateHash {String} For each block, the state of the blockchain is stored in RocksDB, forming a patricia tree. The root of the tree summarizes the state of the blockchain for the given block. 
     * @param beneficiary {String} The public key of the optional beneficiary designated by harvester.
     */
    constructor(height, timestamp, difficulty, feeMultiplier, previousBlockHash, blockTransactionsHash, blockReceiptsHash, stateHash, beneficiary) { 
        
        BlockDTOAllOf.initialize(this, height, timestamp, difficulty, feeMultiplier, previousBlockHash, blockTransactionsHash, blockReceiptsHash, stateHash, beneficiary);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, height, timestamp, difficulty, feeMultiplier, previousBlockHash, blockTransactionsHash, blockReceiptsHash, stateHash, beneficiary) { 
        obj['height'] = height;
        obj['timestamp'] = timestamp;
        obj['difficulty'] = difficulty;
        obj['feeMultiplier'] = feeMultiplier;
        obj['previousBlockHash'] = previousBlockHash;
        obj['blockTransactionsHash'] = blockTransactionsHash;
        obj['blockReceiptsHash'] = blockReceiptsHash;
        obj['stateHash'] = stateHash;
        obj['beneficiary'] = beneficiary;
    }

    /**
     * Constructs a <code>BlockDTOAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlockDTOAllOf} obj Optional instance to populate.
     * @return {module:model/BlockDTOAllOf} The populated <code>BlockDTOAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockDTOAllOf();

            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], ['Number']);
            }
            if (data.hasOwnProperty('timestamp')) {
                obj['timestamp'] = ApiClient.convertToType(data['timestamp'], ['Number']);
            }
            if (data.hasOwnProperty('difficulty')) {
                obj['difficulty'] = ApiClient.convertToType(data['difficulty'], ['Number']);
            }
            if (data.hasOwnProperty('feeMultiplier')) {
                obj['feeMultiplier'] = ApiClient.convertToType(data['feeMultiplier'], 'Number');
            }
            if (data.hasOwnProperty('previousBlockHash')) {
                obj['previousBlockHash'] = ApiClient.convertToType(data['previousBlockHash'], 'String');
            }
            if (data.hasOwnProperty('blockTransactionsHash')) {
                obj['blockTransactionsHash'] = ApiClient.convertToType(data['blockTransactionsHash'], 'String');
            }
            if (data.hasOwnProperty('blockReceiptsHash')) {
                obj['blockReceiptsHash'] = ApiClient.convertToType(data['blockReceiptsHash'], 'String');
            }
            if (data.hasOwnProperty('stateHash')) {
                obj['stateHash'] = ApiClient.convertToType(data['stateHash'], 'String');
            }
            if (data.hasOwnProperty('beneficiary')) {
                obj['beneficiary'] = ApiClient.convertToType(data['beneficiary'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} height
 */
BlockDTOAllOf.prototype['height'] = undefined;

/**
 * @member {Array.<Number>} timestamp
 */
BlockDTOAllOf.prototype['timestamp'] = undefined;

/**
 * @member {Array.<Number>} difficulty
 */
BlockDTOAllOf.prototype['difficulty'] = undefined;

/**
 * The fee multiplier applied to transactions contained in block.
 * @member {Number} feeMultiplier
 */
BlockDTOAllOf.prototype['feeMultiplier'] = undefined;

/**
 * The hash of the previous block.
 * @member {String} previousBlockHash
 */
BlockDTOAllOf.prototype['previousBlockHash'] = undefined;

/**
 * The transactions included in a block are hashed forming a merkle tree. The root of the tree summarizes them. 
 * @member {String} blockTransactionsHash
 */
BlockDTOAllOf.prototype['blockTransactionsHash'] = undefined;

/**
 * The collection of receipts  are hashed into a merkle tree and linked to a block. The block header stores the root hash. 
 * @member {String} blockReceiptsHash
 */
BlockDTOAllOf.prototype['blockReceiptsHash'] = undefined;

/**
 * For each block, the state of the blockchain is stored in RocksDB, forming a patricia tree. The root of the tree summarizes the state of the blockchain for the given block. 
 * @member {String} stateHash
 */
BlockDTOAllOf.prototype['stateHash'] = undefined;

/**
 * The public key of the optional beneficiary designated by harvester.
 * @member {String} beneficiary
 */
BlockDTOAllOf.prototype['beneficiary'] = undefined;






export default BlockDTOAllOf;

