/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The BlockchainScoreDTO model module.
 * @module model/BlockchainScoreDTO
 * @version 0.7.15
 */
class BlockchainScoreDTO {
    /**
     * Constructs a new <code>BlockchainScoreDTO</code>.
     * @alias module:model/BlockchainScoreDTO
     * @param scoreHigh {Array.<Number>} 
     * @param scoreLow {Array.<Number>} 
     */
    constructor(scoreHigh, scoreLow) { 
        
        BlockchainScoreDTO.initialize(this, scoreHigh, scoreLow);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, scoreHigh, scoreLow) { 
        obj['scoreHigh'] = scoreHigh;
        obj['scoreLow'] = scoreLow;
    }

    /**
     * Constructs a <code>BlockchainScoreDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/BlockchainScoreDTO} obj Optional instance to populate.
     * @return {module:model/BlockchainScoreDTO} The populated <code>BlockchainScoreDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new BlockchainScoreDTO();

            if (data.hasOwnProperty('scoreHigh')) {
                obj['scoreHigh'] = ApiClient.convertToType(data['scoreHigh'], ['Number']);
            }
            if (data.hasOwnProperty('scoreLow')) {
                obj['scoreLow'] = ApiClient.convertToType(data['scoreLow'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} scoreHigh
 */
BlockchainScoreDTO.prototype['scoreHigh'] = undefined;

/**
 * @member {Array.<Number>} scoreLow
 */
BlockchainScoreDTO.prototype['scoreLow'] = undefined;






export default BlockchainScoreDTO;

