/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import VerifiableEntityDTO from './VerifiableEntityDTO';





/**
* The CosignatureDTO model module.
* @module model/CosignatureDTO
* @version 0.7.15
*/
export default class CosignatureDTO {
    /**
    * Constructs a new <code>CosignatureDTO</code>.
    * @alias module:model/CosignatureDTO
    * @class
    * @implements module:model/VerifiableEntityDTO
    * @param signature {String} The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    * @param signer {String} The public key of the transaction signer.
    */

    constructor(signature, signer) {
        



        this['signer'] = signer;

        
    }

    /**
    * Constructs a <code>CosignatureDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CosignatureDTO} obj Optional instance to populate.
    * @return {module:model/CosignatureDTO} The populated <code>CosignatureDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CosignatureDTO();

            
            
            VerifiableEntityDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
        }
        return obj;
    }

    /**
    * The public key of the transaction signer.
    * @member {String} signer
    */
    signer = undefined;


    // Implement VerifiableEntityDTO interface:
    /**
    * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    * @member {String} signature
    */
    signature = undefined;







}


