/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import MultisigModificationTypeEnum from './MultisigModificationTypeEnum';





/**
* The CosignatoryModificationDTO model module.
* @module model/CosignatoryModificationDTO
* @version 0.7.15
*/
export default class CosignatoryModificationDTO {
    /**
    * Constructs a new <code>CosignatoryModificationDTO</code>.
    * @alias module:model/CosignatoryModificationDTO
    * @class
    * @param modificationType {module:model/MultisigModificationTypeEnum} 
    * @param cosignatoryPublicKey {String} The public key of the cosignatory account.
    */

    constructor(modificationType, cosignatoryPublicKey) {
        



        this['modificationType'] = modificationType;this['cosignatoryPublicKey'] = cosignatoryPublicKey;

        
    }

    /**
    * Constructs a <code>CosignatoryModificationDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/CosignatoryModificationDTO} obj Optional instance to populate.
    * @return {module:model/CosignatoryModificationDTO} The populated <code>CosignatoryModificationDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CosignatoryModificationDTO();

            
            
            

            if (data.hasOwnProperty('modificationType')) {
                obj['modificationType'] = MultisigModificationTypeEnum.constructFromObject(data['modificationType']);
            }
            if (data.hasOwnProperty('cosignatoryPublicKey')) {
                obj['cosignatoryPublicKey'] = ApiClient.convertToType(data['cosignatoryPublicKey'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/MultisigModificationTypeEnum} modificationType
    */
    modificationType = undefined;
    /**
    * The public key of the cosignatory account.
    * @member {String} cosignatoryPublicKey
    */
    cosignatoryPublicKey = undefined;








}


