/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The CosignatureDTOAllOf model module.
 * @module model/CosignatureDTOAllOf
 * @version 0.7.15
 */
class CosignatureDTOAllOf {
    /**
     * Constructs a new <code>CosignatureDTOAllOf</code>.
     * @alias module:model/CosignatureDTOAllOf
     * @param signer {String} The public key of the transaction signer.
     */
    constructor(signer) { 
        
        CosignatureDTOAllOf.initialize(this, signer);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, signer) { 
        obj['signer'] = signer;
    }

    /**
     * Constructs a <code>CosignatureDTOAllOf</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/CosignatureDTOAllOf} obj Optional instance to populate.
     * @return {module:model/CosignatureDTOAllOf} The populated <code>CosignatureDTOAllOf</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new CosignatureDTOAllOf();

            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The public key of the transaction signer.
 * @member {String} signer
 */
CosignatureDTOAllOf.prototype['signer'] = undefined;






export default CosignatureDTOAllOf;

