/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The DirectionEnum model module.
* @module model/DirectionEnum
* @version 0.7.15
*/
export default class DirectionEnum {
    /**
    * Constructs a new <code>DirectionEnum</code>.
    * The supply modification direction: * 0  - Decrease. * 1  - Increase. 
    * @alias module:model/DirectionEnum
    * @class
    */

    constructor() {
        



        

        
    }

    /**
    * Constructs a <code>DirectionEnum</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/DirectionEnum} obj Optional instance to populate.
    * @return {module:model/DirectionEnum} The populated <code>DirectionEnum</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new DirectionEnum();

            
            
            

        }
        return obj;
    }









}


