/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import DirectionEnum from './DirectionEnum';
import EmbeddedTransactionDTO from './EmbeddedTransactionDTO';
import EntityTypeEnum from './EntityTypeEnum';
import MosaicSupplyChangeTransactionBodyDTO from './MosaicSupplyChangeTransactionBodyDTO';
import NetworkTypeEnum from './NetworkTypeEnum';
import UInt64DTO from './UInt64DTO';





/**
* The EmbeddedMosaicSupplyChangeTransactionDTO model module.
* @module model/EmbeddedMosaicSupplyChangeTransactionDTO
* @version 0.7.15
*/
export default class EmbeddedMosaicSupplyChangeTransactionDTO {
    /**
    * Constructs a new <code>EmbeddedMosaicSupplyChangeTransactionDTO</code>.
    * @alias module:model/EmbeddedMosaicSupplyChangeTransactionDTO
    * @class
    * @implements module:model/EmbeddedTransactionDTO
    * @implements module:model/MosaicSupplyChangeTransactionBodyDTO
    * @param signer {String} The public key of the entity signer formatted as hexadecimal.
    * @param version {module:model/NetworkTypeEnum} 
    * @param type {module:model/EntityTypeEnum} 
    * @param maxFee {module:model/UInt64DTO} 
    * @param deadline {module:model/UInt64DTO} 
    * @param mosaicId {module:model/UInt64DTO} 
    * @param direction {module:model/DirectionEnum} 
    * @param delta {module:model/UInt64DTO} 
    */

    constructor(signer, version, type, maxFee, deadline, mosaicId, direction, delta) {
        



        

        
    }

    /**
    * Constructs a <code>EmbeddedMosaicSupplyChangeTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EmbeddedMosaicSupplyChangeTransactionDTO} obj Optional instance to populate.
    * @return {module:model/EmbeddedMosaicSupplyChangeTransactionDTO} The populated <code>EmbeddedMosaicSupplyChangeTransactionDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmbeddedMosaicSupplyChangeTransactionDTO();

            
            
            EmbeddedTransactionDTO.constructFromObject(data, obj);MosaicSupplyChangeTransactionBodyDTO.constructFromObject(data, obj);

        }
        return obj;
    }



    // Implement EmbeddedTransactionDTO interface:
    /**
    * The public key of the entity signer formatted as hexadecimal.
    * @member {String} signer
    */
    signer = undefined;
/**
    * @member {module:model/NetworkTypeEnum} version
    */
    version = undefined;
/**
    * @member {module:model/EntityTypeEnum} type
    */
    type = undefined;
/**
    * @member {module:model/UInt64DTO} max_fee
    */
    max_fee = undefined;
/**
    * @member {module:model/UInt64DTO} deadline
    */
    deadline = undefined;

    // Implement MosaicSupplyChangeTransactionBodyDTO interface:
    /**
    * @member {module:model/UInt64DTO} mosaicId
    */
    mosaicId = undefined;
/**
    * @member {module:model/DirectionEnum} direction
    */
    direction = undefined;
/**
    * @member {module:model/UInt64DTO} delta
    */
    delta = undefined;







}


