/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CosignatoryModificationDTO from './CosignatoryModificationDTO';
import EmbeddedTransactionDTO from './EmbeddedTransactionDTO';
import ModifyMultisigAccountTransactionBodyDTO from './ModifyMultisigAccountTransactionBodyDTO';

/**
 * The EmbeddedModifyMultisigAccountTransactionDTO model module.
 * @module model/EmbeddedModifyMultisigAccountTransactionDTO
 * @version 0.7.15
 */
class EmbeddedModifyMultisigAccountTransactionDTO {
    /**
     * Constructs a new <code>EmbeddedModifyMultisigAccountTransactionDTO</code>.
     * @alias module:model/EmbeddedModifyMultisigAccountTransactionDTO
     * @implements module:model/EmbeddedTransactionDTO
     * @implements module:model/ModifyMultisigAccountTransactionBodyDTO
     */
    constructor() { 
        EmbeddedTransactionDTO.initialize(this);ModifyMultisigAccountTransactionBodyDTO.initialize(this, minRemovalDelta, minApprovalDelta, modifications);
        EmbeddedModifyMultisigAccountTransactionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
        obj['max_fee'] = maxFee;
        obj['deadline'] = deadline;
        obj['minRemovalDelta'] = minRemovalDelta;
        obj['minApprovalDelta'] = minApprovalDelta;
        obj['modifications'] = modifications;
    }

    /**
     * Constructs a <code>EmbeddedModifyMultisigAccountTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmbeddedModifyMultisigAccountTransactionDTO} obj Optional instance to populate.
     * @return {module:model/EmbeddedModifyMultisigAccountTransactionDTO} The populated <code>EmbeddedModifyMultisigAccountTransactionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmbeddedModifyMultisigAccountTransactionDTO();
            EmbeddedTransactionDTO.constructFromObject(data, obj);
            ModifyMultisigAccountTransactionBodyDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('max_fee')) {
                obj['max_fee'] = ApiClient.convertToType(data['max_fee'], ['Number']);
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
            if (data.hasOwnProperty('minRemovalDelta')) {
                obj['minRemovalDelta'] = ApiClient.convertToType(data['minRemovalDelta'], 'Number');
            }
            if (data.hasOwnProperty('minApprovalDelta')) {
                obj['minApprovalDelta'] = ApiClient.convertToType(data['minApprovalDelta'], 'Number');
            }
            if (data.hasOwnProperty('modifications')) {
                obj['modifications'] = ApiClient.convertToType(data['modifications'], [CosignatoryModificationDTO]);
            }
        }
        return obj;
    }


}

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
EmbeddedModifyMultisigAccountTransactionDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
EmbeddedModifyMultisigAccountTransactionDTO.prototype['version'] = undefined;

/**
 * @member {Object} type
 */
EmbeddedModifyMultisigAccountTransactionDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} max_fee
 */
EmbeddedModifyMultisigAccountTransactionDTO.prototype['max_fee'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
EmbeddedModifyMultisigAccountTransactionDTO.prototype['deadline'] = undefined;

/**
 * The number of signatures needed to remove a cosignatory. If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories. 
 * @member {Number} minRemovalDelta
 */
EmbeddedModifyMultisigAccountTransactionDTO.prototype['minRemovalDelta'] = undefined;

/**
 * The number of signatures needed to approve a transaction. If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories. 
 * @member {Number} minApprovalDelta
 */
EmbeddedModifyMultisigAccountTransactionDTO.prototype['minApprovalDelta'] = undefined;

/**
 * The array of cosignatory accounts to add or delete.
 * @member {Array.<module:model/CosignatoryModificationDTO>} modifications
 */
EmbeddedModifyMultisigAccountTransactionDTO.prototype['modifications'] = undefined;


// Implement EmbeddedTransactionDTO interface:
// Implement ModifyMultisigAccountTransactionBodyDTO interface:
/**
 * @member {Object} type
 */
ModifyMultisigAccountTransactionBodyDTO.prototype['type'] = undefined;
/**
 * The number of signatures needed to remove a cosignatory. If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories. 
 * @member {Number} minRemovalDelta
 */
ModifyMultisigAccountTransactionBodyDTO.prototype['minRemovalDelta'] = undefined;
/**
 * The number of signatures needed to approve a transaction. If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories. 
 * @member {Number} minApprovalDelta
 */
ModifyMultisigAccountTransactionBodyDTO.prototype['minApprovalDelta'] = undefined;
/**
 * The array of cosignatory accounts to add or delete.
 * @member {Array.<module:model/CosignatoryModificationDTO>} modifications
 */
ModifyMultisigAccountTransactionBodyDTO.prototype['modifications'] = undefined;




export default EmbeddedModifyMultisigAccountTransactionDTO;

