/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import EmbeddedTransactionDTO from './EmbeddedTransactionDTO';
import EntityTypeEnum from './EntityTypeEnum';
import HashAlgorithmEnum from './HashAlgorithmEnum';
import NetworkTypeEnum from './NetworkTypeEnum';
import SecretLockTransactionBodyDTO from './SecretLockTransactionBodyDTO';
import UInt64DTO from './UInt64DTO';





/**
* The EmbeddedSecretLockTransactionDTO model module.
* @module model/EmbeddedSecretLockTransactionDTO
* @version 0.7.15
*/
export default class EmbeddedSecretLockTransactionDTO {
    /**
    * Constructs a new <code>EmbeddedSecretLockTransactionDTO</code>.
    * @alias module:model/EmbeddedSecretLockTransactionDTO
    * @class
    * @implements module:model/EmbeddedTransactionDTO
    * @implements module:model/SecretLockTransactionBodyDTO
    * @param signer {String} The public key of the entity signer formatted as hexadecimal.
    * @param version {module:model/NetworkTypeEnum} 
    * @param type {module:model/EntityTypeEnum} 
    * @param maxFee {module:model/UInt64DTO} 
    * @param deadline {module:model/UInt64DTO} 
    * @param duration {module:model/UInt64DTO} 
    * @param mosaicId {module:model/UInt64DTO} 
    * @param amount {module:model/UInt64DTO} 
    * @param hashAlgorithm {module:model/HashAlgorithmEnum} 
    * @param secret {String} The proof hashed.
    * @param recipient {String} The address in hexadecimal that will receive the funds once the transaction is unlocked.
    */

    constructor(signer, version, type, maxFee, deadline, duration, mosaicId, amount, hashAlgorithm, secret, recipient) {
        



        

        
    }

    /**
    * Constructs a <code>EmbeddedSecretLockTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EmbeddedSecretLockTransactionDTO} obj Optional instance to populate.
    * @return {module:model/EmbeddedSecretLockTransactionDTO} The populated <code>EmbeddedSecretLockTransactionDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmbeddedSecretLockTransactionDTO();

            
            
            EmbeddedTransactionDTO.constructFromObject(data, obj);SecretLockTransactionBodyDTO.constructFromObject(data, obj);

        }
        return obj;
    }



    // Implement EmbeddedTransactionDTO interface:
    /**
    * The public key of the entity signer formatted as hexadecimal.
    * @member {String} signer
    */
    signer = undefined;
/**
    * @member {module:model/NetworkTypeEnum} version
    */
    version = undefined;
/**
    * @member {module:model/EntityTypeEnum} type
    */
    type = undefined;
/**
    * @member {module:model/UInt64DTO} max_fee
    */
    max_fee = undefined;
/**
    * @member {module:model/UInt64DTO} deadline
    */
    deadline = undefined;

    // Implement SecretLockTransactionBodyDTO interface:
    /**
    * @member {module:model/UInt64DTO} duration
    */
    duration = undefined;
/**
    * @member {module:model/UInt64DTO} mosaicId
    */
    mosaicId = undefined;
/**
    * @member {module:model/UInt64DTO} amount
    */
    amount = undefined;
/**
    * @member {module:model/HashAlgorithmEnum} hashAlgorithm
    */
    hashAlgorithm = undefined;
/**
    * The proof hashed.
    * @member {String} secret
    */
    secret = undefined;
/**
    * The address in hexadecimal that will receive the funds once the transaction is unlocked.
    * @member {String} recipient
    */
    recipient = undefined;







}


