/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import EmbeddedTransactionDTO from './EmbeddedTransactionDTO';
import EmbeddedTransactionMetaDTO from './EmbeddedTransactionMetaDTO';





/**
* The EmbeddedTransactionInfoDTO model module.
* @module model/EmbeddedTransactionInfoDTO
* @version 0.7.15
*/
export default class EmbeddedTransactionInfoDTO {
    /**
    * Constructs a new <code>EmbeddedTransactionInfoDTO</code>.
    * @alias module:model/EmbeddedTransactionInfoDTO
    * @class
    * @param meta {module:model/EmbeddedTransactionMetaDTO} 
    * @param transaction {module:model/EmbeddedTransactionDTO} 
    */

    constructor(meta, transaction) {
        



        this['meta'] = meta;this['transaction'] = transaction;

        
    }

    /**
    * Constructs a <code>EmbeddedTransactionInfoDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EmbeddedTransactionInfoDTO} obj Optional instance to populate.
    * @return {module:model/EmbeddedTransactionInfoDTO} The populated <code>EmbeddedTransactionInfoDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmbeddedTransactionInfoDTO();

            
            
            

            if (data.hasOwnProperty('meta')) {
                obj['meta'] = EmbeddedTransactionMetaDTO.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('transaction')) {
                obj['transaction'] = EmbeddedTransactionDTO.constructFromObject(data['transaction']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/EmbeddedTransactionMetaDTO} meta
    */
    meta = undefined;
    /**
    * @member {module:model/EmbeddedTransactionDTO} transaction
    */
    transaction = undefined;








}


