/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import DirectionEnum from './DirectionEnum';
import EmbeddedTransactionDTO from './EmbeddedTransactionDTO';
import MosaicSupplyChangeTransactionBodyDTO from './MosaicSupplyChangeTransactionBodyDTO';

/**
 * The EmbeddedMosaicSupplyChangeTransactionDTO model module.
 * @module model/EmbeddedMosaicSupplyChangeTransactionDTO
 * @version 0.7.15
 */
class EmbeddedMosaicSupplyChangeTransactionDTO {
    /**
     * Constructs a new <code>EmbeddedMosaicSupplyChangeTransactionDTO</code>.
     * @alias module:model/EmbeddedMosaicSupplyChangeTransactionDTO
     * @implements module:model/EmbeddedTransactionDTO
     * @implements module:model/MosaicSupplyChangeTransactionBodyDTO
     */
    constructor() { 
        EmbeddedTransactionDTO.initialize(this);MosaicSupplyChangeTransactionBodyDTO.initialize(this, mosaicId, direction, delta);
        EmbeddedMosaicSupplyChangeTransactionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
        obj['max_fee'] = maxFee;
        obj['deadline'] = deadline;
        obj['mosaicId'] = mosaicId;
        obj['direction'] = direction;
        obj['delta'] = delta;
    }

    /**
     * Constructs a <code>EmbeddedMosaicSupplyChangeTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmbeddedMosaicSupplyChangeTransactionDTO} obj Optional instance to populate.
     * @return {module:model/EmbeddedMosaicSupplyChangeTransactionDTO} The populated <code>EmbeddedMosaicSupplyChangeTransactionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmbeddedMosaicSupplyChangeTransactionDTO();
            EmbeddedTransactionDTO.constructFromObject(data, obj);
            MosaicSupplyChangeTransactionBodyDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('max_fee')) {
                obj['max_fee'] = ApiClient.convertToType(data['max_fee'], ['Number']);
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
            if (data.hasOwnProperty('mosaicId')) {
                obj['mosaicId'] = ApiClient.convertToType(data['mosaicId'], ['Number']);
            }
            if (data.hasOwnProperty('direction')) {
                obj['direction'] = DirectionEnum.constructFromObject(data['direction']);
            }
            if (data.hasOwnProperty('delta')) {
                obj['delta'] = ApiClient.convertToType(data['delta'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
EmbeddedMosaicSupplyChangeTransactionDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
EmbeddedMosaicSupplyChangeTransactionDTO.prototype['version'] = undefined;

/**
 * @member {Object} type
 */
EmbeddedMosaicSupplyChangeTransactionDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} max_fee
 */
EmbeddedMosaicSupplyChangeTransactionDTO.prototype['max_fee'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
EmbeddedMosaicSupplyChangeTransactionDTO.prototype['deadline'] = undefined;

/**
 * @member {Array.<Number>} mosaicId
 */
EmbeddedMosaicSupplyChangeTransactionDTO.prototype['mosaicId'] = undefined;

/**
 * @member {module:model/DirectionEnum} direction
 */
EmbeddedMosaicSupplyChangeTransactionDTO.prototype['direction'] = undefined;

/**
 * @member {Array.<Number>} delta
 */
EmbeddedMosaicSupplyChangeTransactionDTO.prototype['delta'] = undefined;


// Implement EmbeddedTransactionDTO interface:
// Implement MosaicSupplyChangeTransactionBodyDTO interface:
/**
 * @member {Object} type
 */
MosaicSupplyChangeTransactionBodyDTO.prototype['type'] = undefined;
/**
 * @member {Array.<Number>} mosaicId
 */
MosaicSupplyChangeTransactionBodyDTO.prototype['mosaicId'] = undefined;
/**
 * @member {module:model/DirectionEnum} direction
 */
MosaicSupplyChangeTransactionBodyDTO.prototype['direction'] = undefined;
/**
 * @member {Array.<Number>} delta
 */
MosaicSupplyChangeTransactionBodyDTO.prototype['delta'] = undefined;




export default EmbeddedMosaicSupplyChangeTransactionDTO;

