/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AliasActionEnum from './AliasActionEnum';
import EmbeddedTransactionDTO from './EmbeddedTransactionDTO';
import MosaicAliasTransactionBodyDTO from './MosaicAliasTransactionBodyDTO';

/**
 * The EmbeddedMosaicAliasTransactionDTO model module.
 * @module model/EmbeddedMosaicAliasTransactionDTO
 * @version 0.7.15
 */
class EmbeddedMosaicAliasTransactionDTO {
    /**
     * Constructs a new <code>EmbeddedMosaicAliasTransactionDTO</code>.
     * @alias module:model/EmbeddedMosaicAliasTransactionDTO
     * @implements module:model/EmbeddedTransactionDTO
     * @implements module:model/MosaicAliasTransactionBodyDTO
     */
    constructor() { 
        EmbeddedTransactionDTO.initialize(this);MosaicAliasTransactionBodyDTO.initialize(this, aliasAction, namespaceId);
        EmbeddedMosaicAliasTransactionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
        obj['max_fee'] = maxFee;
        obj['deadline'] = deadline;
        obj['aliasAction'] = aliasAction;
        obj['namespaceId'] = namespaceId;
    }

    /**
     * Constructs a <code>EmbeddedMosaicAliasTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmbeddedMosaicAliasTransactionDTO} obj Optional instance to populate.
     * @return {module:model/EmbeddedMosaicAliasTransactionDTO} The populated <code>EmbeddedMosaicAliasTransactionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmbeddedMosaicAliasTransactionDTO();
            EmbeddedTransactionDTO.constructFromObject(data, obj);
            MosaicAliasTransactionBodyDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('max_fee')) {
                obj['max_fee'] = ApiClient.convertToType(data['max_fee'], ['Number']);
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
            if (data.hasOwnProperty('aliasAction')) {
                obj['aliasAction'] = AliasActionEnum.constructFromObject(data['aliasAction']);
            }
            if (data.hasOwnProperty('namespaceId')) {
                obj['namespaceId'] = ApiClient.convertToType(data['namespaceId'], ['Number']);
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
EmbeddedMosaicAliasTransactionDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
EmbeddedMosaicAliasTransactionDTO.prototype['version'] = undefined;

/**
 * @member {Object} type
 */
EmbeddedMosaicAliasTransactionDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} max_fee
 */
EmbeddedMosaicAliasTransactionDTO.prototype['max_fee'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
EmbeddedMosaicAliasTransactionDTO.prototype['deadline'] = undefined;

/**
 * @member {module:model/AliasActionEnum} aliasAction
 */
EmbeddedMosaicAliasTransactionDTO.prototype['aliasAction'] = undefined;

/**
 * @member {Array.<Number>} namespaceId
 */
EmbeddedMosaicAliasTransactionDTO.prototype['namespaceId'] = undefined;

/**
 * @member {Array.<Number>} address
 */
EmbeddedMosaicAliasTransactionDTO.prototype['address'] = undefined;


// Implement EmbeddedTransactionDTO interface:
// Implement MosaicAliasTransactionBodyDTO interface:
/**
 * @member {Object} type
 */
MosaicAliasTransactionBodyDTO.prototype['type'] = undefined;
/**
 * @member {module:model/AliasActionEnum} aliasAction
 */
MosaicAliasTransactionBodyDTO.prototype['aliasAction'] = undefined;
/**
 * @member {Array.<Number>} namespaceId
 */
MosaicAliasTransactionBodyDTO.prototype['namespaceId'] = undefined;
/**
 * @member {Array.<Number>} address
 */
MosaicAliasTransactionBodyDTO.prototype['address'] = undefined;




export default EmbeddedMosaicAliasTransactionDTO;

