/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntityDTO from './EntityDTO';
import EntityTypeEnum from './EntityTypeEnum';
import TransactionBodyDTO from './TransactionBodyDTO';

/**
 * The EmbeddedTransactionDTO model module.
 * @module model/EmbeddedTransactionDTO
 * @version 0.7.15
 */
class EmbeddedTransactionDTO {
    /**
     * Constructs a new <code>EmbeddedTransactionDTO</code>.
     * @alias module:model/EmbeddedTransactionDTO
     * @implements module:model/EntityDTO
     * @implements module:model/TransactionBodyDTO
     */
    constructor() { 
        EntityDTO.initialize(this, signer, version, type);TransactionBodyDTO.initialize(this, maxFee, deadline);
        EmbeddedTransactionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
        obj['max_fee'] = maxFee;
        obj['deadline'] = deadline;
    }

    /**
     * Constructs a <code>EmbeddedTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmbeddedTransactionDTO} obj Optional instance to populate.
     * @return {module:model/EmbeddedTransactionDTO} The populated <code>EmbeddedTransactionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmbeddedTransactionDTO();
            EntityDTO.constructFromObject(data, obj);
            TransactionBodyDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = EntityTypeEnum.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('max_fee')) {
                obj['max_fee'] = ApiClient.convertToType(data['max_fee'], ['Number']);
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
EmbeddedTransactionDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
EmbeddedTransactionDTO.prototype['version'] = undefined;

/**
 * @member {module:model/EntityTypeEnum} type
 */
EmbeddedTransactionDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} max_fee
 */
EmbeddedTransactionDTO.prototype['max_fee'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
EmbeddedTransactionDTO.prototype['deadline'] = undefined;


// Implement EntityDTO interface:
/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
EntityDTO.prototype['signer'] = undefined;
/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
EntityDTO.prototype['version'] = undefined;
/**
 * @member {module:model/EntityTypeEnum} type
 */
EntityDTO.prototype['type'] = undefined;
// Implement TransactionBodyDTO interface:
/**
 * @member {Array.<Number>} max_fee
 */
TransactionBodyDTO.prototype['max_fee'] = undefined;
/**
 * @member {Array.<Number>} deadline
 */
TransactionBodyDTO.prototype['deadline'] = undefined;




export default EmbeddedTransactionDTO;

