/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EmbeddedTransactionDTO from './EmbeddedTransactionDTO';
import EmbeddedTransactionMetaDTO from './EmbeddedTransactionMetaDTO';

/**
 * The EmbeddedTransactionInfoDTO model module.
 * @module model/EmbeddedTransactionInfoDTO
 * @version 0.7.15
 */
class EmbeddedTransactionInfoDTO {
    /**
     * Constructs a new <code>EmbeddedTransactionInfoDTO</code>.
     * @alias module:model/EmbeddedTransactionInfoDTO
     * @param meta {module:model/EmbeddedTransactionMetaDTO} 
     * @param transaction {module:model/EmbeddedTransactionDTO} 
     */
    constructor(meta, transaction) { 
        
        EmbeddedTransactionInfoDTO.initialize(this, meta, transaction);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, meta, transaction) { 
        obj['meta'] = meta;
        obj['transaction'] = transaction;
    }

    /**
     * Constructs a <code>EmbeddedTransactionInfoDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EmbeddedTransactionInfoDTO} obj Optional instance to populate.
     * @return {module:model/EmbeddedTransactionInfoDTO} The populated <code>EmbeddedTransactionInfoDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmbeddedTransactionInfoDTO();

            if (data.hasOwnProperty('meta')) {
                obj['meta'] = EmbeddedTransactionMetaDTO.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('transaction')) {
                obj['transaction'] = EmbeddedTransactionDTO.constructFromObject(data['transaction']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/EmbeddedTransactionMetaDTO} meta
 */
EmbeddedTransactionInfoDTO.prototype['meta'] = undefined;

/**
 * @member {module:model/EmbeddedTransactionDTO} transaction
 */
EmbeddedTransactionInfoDTO.prototype['transaction'] = undefined;






export default EmbeddedTransactionInfoDTO;

