/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import EmbeddedTransactionDTO from './EmbeddedTransactionDTO';
import EntityTypeEnum from './EntityTypeEnum';
import HashLockTransactionDTO from './HashLockTransactionDTO';
import MosaicDTO from './MosaicDTO';
import NetworkTypeEnum from './NetworkTypeEnum';
import UInt64DTO from './UInt64DTO';





/**
* The EmbeddedHashLockTransactionDTO model module.
* @module model/EmbeddedHashLockTransactionDTO
* @version 0.7.15
*/
export default class EmbeddedHashLockTransactionDTO {
    /**
    * Constructs a new <code>EmbeddedHashLockTransactionDTO</code>.
    * @alias module:model/EmbeddedHashLockTransactionDTO
    * @class
    * @implements module:model/EmbeddedTransactionDTO
    * @implements module:model/HashLockTransactionDTO
    * @param signer {String} The public key of the entity signer formatted as hexadecimal.
    * @param version {module:model/NetworkTypeEnum} 
    * @param type {module:model/EntityTypeEnum} 
    * @param maxFee {module:model/UInt64DTO} 
    * @param deadline {module:model/UInt64DTO} 
    * @param signature {String} The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    * @param mosaic {module:model/MosaicDTO} 
    * @param duration {module:model/MosaicDTO} 
    * @param hash {String} The aggregate bonded transaction hash that has to be confirmed before unlocking the mosaics. 
    */

    constructor(signer, version, type, maxFee, deadline, signature, mosaic, duration, hash) {
        



        

        
    }

    /**
    * Constructs a <code>EmbeddedHashLockTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/EmbeddedHashLockTransactionDTO} obj Optional instance to populate.
    * @return {module:model/EmbeddedHashLockTransactionDTO} The populated <code>EmbeddedHashLockTransactionDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EmbeddedHashLockTransactionDTO();

            
            
            EmbeddedTransactionDTO.constructFromObject(data, obj);HashLockTransactionDTO.constructFromObject(data, obj);

        }
        return obj;
    }



    // Implement EmbeddedTransactionDTO interface:
    /**
    * The public key of the entity signer formatted as hexadecimal.
    * @member {String} signer
    */
    signer = undefined;
/**
    * @member {module:model/NetworkTypeEnum} version
    */
    version = undefined;
/**
    * @member {module:model/EntityTypeEnum} type
    */
    type = undefined;
/**
    * @member {module:model/UInt64DTO} max_fee
    */
    max_fee = undefined;
/**
    * @member {module:model/UInt64DTO} deadline
    */
    deadline = undefined;

    // Implement HashLockTransactionDTO interface:
    /**
    * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    * @member {String} signature
    */
    signature = undefined;
/**
    * The public key of the entity signer formatted as hexadecimal.
    * @member {String} signer
    */
    signer = undefined;
/**
    * @member {module:model/NetworkTypeEnum} version
    */
    version = undefined;
/**
    * @member {module:model/EntityTypeEnum} type
    */
    type = undefined;
/**
    * @member {module:model/UInt64DTO} max_fee
    */
    max_fee = undefined;
/**
    * @member {module:model/UInt64DTO} deadline
    */
    deadline = undefined;
/**
    * @member {module:model/MosaicDTO} mosaic
    */
    mosaic = undefined;
/**
    * @member {module:model/MosaicDTO} duration
    */
    duration = undefined;
/**
    * The aggregate bonded transaction hash that has to be confirmed before unlocking the mosaics. 
    * @member {String} hash
    */
    hash = undefined;







}


