/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntityTypeEnum from './EntityTypeEnum';

/**
 * The EntityDTO model module.
 * @module model/EntityDTO
 * @version 0.7.15
 */
class EntityDTO {
    /**
     * Constructs a new <code>EntityDTO</code>.
     * @alias module:model/EntityDTO
     * @param signer {String} The public key of the entity signer formatted as hexadecimal.
     * @param version {Number} The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
     * @param type {module:model/EntityTypeEnum} 
     */
    constructor(signer, version, type) { 
        
        EntityDTO.initialize(this, signer, version, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, signer, version, type) { 
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>EntityDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/EntityDTO} obj Optional instance to populate.
     * @return {module:model/EntityDTO} The populated <code>EntityDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new EntityDTO();

            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = EntityTypeEnum.constructFromObject(data['type']);
            }
        }
        return obj;
    }


}

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
EntityDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
EntityDTO.prototype['version'] = undefined;

/**
 * @member {module:model/EntityTypeEnum} type
 */
EntityDTO.prototype['type'] = undefined;






export default EntityDTO;

