/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MosaicDTO from './MosaicDTO';

/**
 * The HashLockTransactionBodyDTO model module.
 * @module model/HashLockTransactionBodyDTO
 * @version 0.7.15
 */
class HashLockTransactionBodyDTO {
    /**
     * Constructs a new <code>HashLockTransactionBodyDTO</code>.
     * @alias module:model/HashLockTransactionBodyDTO
     * @param mosaic {module:model/MosaicDTO} 
     * @param duration {module:model/MosaicDTO} 
     * @param hash {String} The aggregate bonded transaction hash that has to be confirmed before unlocking the mosaics. 
     */
    constructor(mosaic, duration, hash) { 
        
        HashLockTransactionBodyDTO.initialize(this, mosaic, duration, hash);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mosaic, duration, hash) { 
        obj['mosaic'] = mosaic;
        obj['duration'] = duration;
        obj['hash'] = hash;
    }

    /**
     * Constructs a <code>HashLockTransactionBodyDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HashLockTransactionBodyDTO} obj Optional instance to populate.
     * @return {module:model/HashLockTransactionBodyDTO} The populated <code>HashLockTransactionBodyDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HashLockTransactionBodyDTO();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('mosaic')) {
                obj['mosaic'] = MosaicDTO.constructFromObject(data['mosaic']);
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = MosaicDTO.constructFromObject(data['duration']);
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object} type
 */
HashLockTransactionBodyDTO.prototype['type'] = undefined;

/**
 * @member {module:model/MosaicDTO} mosaic
 */
HashLockTransactionBodyDTO.prototype['mosaic'] = undefined;

/**
 * @member {module:model/MosaicDTO} duration
 */
HashLockTransactionBodyDTO.prototype['duration'] = undefined;

/**
 * The aggregate bonded transaction hash that has to be confirmed before unlocking the mosaics. 
 * @member {String} hash
 */
HashLockTransactionBodyDTO.prototype['hash'] = undefined;






export default HashLockTransactionBodyDTO;

