/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HashLockTransactionBodyDTO from './HashLockTransactionBodyDTO';
import MosaicDTO from './MosaicDTO';
import TransactionDTO from './TransactionDTO';

/**
 * The HashLockTransactionDTO model module.
 * @module model/HashLockTransactionDTO
 * @version 0.7.15
 */
class HashLockTransactionDTO {
    /**
     * Constructs a new <code>HashLockTransactionDTO</code>.
     * Transaction to lock funds before sending an aggregate bonded transaction.
     * @alias module:model/HashLockTransactionDTO
     * @implements module:model/TransactionDTO
     * @implements module:model/HashLockTransactionBodyDTO
     */
    constructor() { 
        TransactionDTO.initialize(this);HashLockTransactionBodyDTO.initialize(this, mosaic, duration, hash);
        HashLockTransactionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['signature'] = signature;
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
        obj['max_fee'] = maxFee;
        obj['deadline'] = deadline;
        obj['mosaic'] = mosaic;
        obj['duration'] = duration;
        obj['hash'] = hash;
    }

    /**
     * Constructs a <code>HashLockTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/HashLockTransactionDTO} obj Optional instance to populate.
     * @return {module:model/HashLockTransactionDTO} The populated <code>HashLockTransactionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HashLockTransactionDTO();
            TransactionDTO.constructFromObject(data, obj);
            HashLockTransactionBodyDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('max_fee')) {
                obj['max_fee'] = ApiClient.convertToType(data['max_fee'], ['Number']);
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
            if (data.hasOwnProperty('mosaic')) {
                obj['mosaic'] = MosaicDTO.constructFromObject(data['mosaic']);
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = MosaicDTO.constructFromObject(data['duration']);
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
 * @member {String} signature
 */
HashLockTransactionDTO.prototype['signature'] = undefined;

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
HashLockTransactionDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
HashLockTransactionDTO.prototype['version'] = undefined;

/**
 * @member {Object} type
 */
HashLockTransactionDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} max_fee
 */
HashLockTransactionDTO.prototype['max_fee'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
HashLockTransactionDTO.prototype['deadline'] = undefined;

/**
 * @member {module:model/MosaicDTO} mosaic
 */
HashLockTransactionDTO.prototype['mosaic'] = undefined;

/**
 * @member {module:model/MosaicDTO} duration
 */
HashLockTransactionDTO.prototype['duration'] = undefined;

/**
 * The aggregate bonded transaction hash that has to be confirmed before unlocking the mosaics. 
 * @member {String} hash
 */
HashLockTransactionDTO.prototype['hash'] = undefined;


// Implement TransactionDTO interface:
// Implement HashLockTransactionBodyDTO interface:
/**
 * @member {Object} type
 */
HashLockTransactionBodyDTO.prototype['type'] = undefined;
/**
 * @member {module:model/MosaicDTO} mosaic
 */
HashLockTransactionBodyDTO.prototype['mosaic'] = undefined;
/**
 * @member {module:model/MosaicDTO} duration
 */
HashLockTransactionBodyDTO.prototype['duration'] = undefined;
/**
 * The aggregate bonded transaction hash that has to be confirmed before unlocking the mosaics. 
 * @member {String} hash
 */
HashLockTransactionBodyDTO.prototype['hash'] = undefined;




export default HashLockTransactionDTO;

