/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import MosaicDTO from './MosaicDTO';





/**
* The HashLockTransactionBodyDTO model module.
* @module model/HashLockTransactionBodyDTO
* @version 0.7.15
*/
export default class HashLockTransactionBodyDTO {
    /**
    * Constructs a new <code>HashLockTransactionBodyDTO</code>.
    * @alias module:model/HashLockTransactionBodyDTO
    * @class
    * @param mosaic {module:model/MosaicDTO} 
    * @param duration {module:model/MosaicDTO} 
    * @param hash {String} The aggregate bonded transaction hash that has to be confirmed before unlocking the mosaics. 
    */

    constructor(mosaic, duration, hash) {
        



        this['mosaic'] = mosaic;this['duration'] = duration;this['hash'] = hash;

        
    }

    /**
    * Constructs a <code>HashLockTransactionBodyDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HashLockTransactionBodyDTO} obj Optional instance to populate.
    * @return {module:model/HashLockTransactionBodyDTO} The populated <code>HashLockTransactionBodyDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HashLockTransactionBodyDTO();

            
            
            

            if (data.hasOwnProperty('mosaic')) {
                obj['mosaic'] = MosaicDTO.constructFromObject(data['mosaic']);
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = MosaicDTO.constructFromObject(data['duration']);
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/MosaicDTO} mosaic
    */
    mosaic = undefined;
    /**
    * @member {module:model/MosaicDTO} duration
    */
    duration = undefined;
    /**
    * The aggregate bonded transaction hash that has to be confirmed before unlocking the mosaics. 
    * @member {String} hash
    */
    hash = undefined;








}


