/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import UInt64DTO from './UInt64DTO';





/**
* The HeightInfoDTO model module.
* @module model/HeightInfoDTO
* @version 0.7.15
*/
export default class HeightInfoDTO {
    /**
    * Constructs a new <code>HeightInfoDTO</code>.
    * @alias module:model/HeightInfoDTO
    * @class
    * @param height {module:model/UInt64DTO} 
    */

    constructor(height) {
        

        
        HeightDTO.initialize(this, height);
    }



        this['height'] = height;

        
    }

    /**
    * Constructs a <code>HeightInfoDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/HeightInfoDTO} obj Optional instance to populate.
    * @return {module:model/HeightInfoDTO} The populated <code>HeightInfoDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new HeightInfoDTO();

            
            
            

            if (data.hasOwnProperty('height')) {
                obj['height'] = UInt64DTO.constructFromObject(data['height']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/UInt64DTO} height
    */
    height = undefined;



/**
 * @member {Array.<Number>} height
 */
HeightDTO.prototype['height'] = undefined;





}

export default HeightDTO;

