/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import ReceiptDTO from './ReceiptDTO';
import ReceiptTypeEnum from './ReceiptTypeEnum';
import UInt64DTO from './UInt64DTO';





/**
* The InflationReceiptDTO model module.
* @module model/InflationReceiptDTO
* @version 0.7.15
*/
export default class InflationReceiptDTO {
    /**
    * Constructs a new <code>InflationReceiptDTO</code>.
    * Native currency mosaics were created due to inflation.
    * @alias module:model/InflationReceiptDTO
    * @class
    * @implements module:model/ReceiptDTO
    * @param version {Number} The version of the receipt.
    * @param type {module:model/ReceiptTypeEnum} 
    * @param mosaicId {module:model/UInt64DTO} 
    * @param amount {module:model/UInt64DTO} 
    */

    constructor(version, type, mosaicId, amount) {
        



        this['mosaicId'] = mosaicId;this['amount'] = amount;

        
    }

    /**
    * Constructs a <code>InflationReceiptDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/InflationReceiptDTO} obj Optional instance to populate.
    * @return {module:model/InflationReceiptDTO} The populated <code>InflationReceiptDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new InflationReceiptDTO();

            
            
            ReceiptDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('mosaicId')) {
                obj['mosaicId'] = UInt64DTO.constructFromObject(data['mosaicId']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = UInt64DTO.constructFromObject(data['amount']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/UInt64DTO} mosaicId
    */
    mosaicId = undefined;
    /**
    * @member {module:model/UInt64DTO} amount
    */
    amount = undefined;


    // Implement ReceiptDTO interface:
    /**
    * The version of the receipt.
    * @member {Number} version
    */
    version = undefined;
/**
    * @member {module:model/ReceiptTypeEnum} type
    */
    type = undefined;







}


