/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The MerklePathItem model module.
* @module model/MerklePathItem
* @version 0.7.15
*/
export default class MerklePathItem {
    /**
     * Constructs a new <code>MerklePathItem</code>.
     * @alias module:model/MerklePathItem
     */
    constructor() { 
        
        MerklePathItem.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MerklePathItem</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerklePathItem} obj Optional instance to populate.
     * @return {module:model/MerklePathItem} The populated <code>MerklePathItem</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerklePathItem();

            if (data.hasOwnProperty('position')) {
                obj['position'] = ApiClient.convertToType(data['position'], 'Number');
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Number} position
 */
MerklePathItem.prototype['position'] = undefined;

/**
 * @member {String} hash
 */
MerklePathItem.prototype['hash'] = undefined;






export default MerklePathItem;

