/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MerklePathItem from './MerklePathItem';

/**
 * The MerkleProofInfoPayload model module.
 * @module model/MerkleProofInfoPayload
 * @version 0.7.15
 */
class MerkleProofInfoPayload {
    /**
     * Constructs a new <code>MerkleProofInfoPayload</code>.
     * @alias module:model/MerkleProofInfoPayload
     */
    constructor() { 
        
        MerkleProofInfoPayload.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MerkleProofInfoPayload</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MerkleProofInfoPayload} obj Optional instance to populate.
     * @return {module:model/MerkleProofInfoPayload} The populated <code>MerkleProofInfoPayload</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MerkleProofInfoPayload();

            if (data.hasOwnProperty('merklePath')) {
                obj['merklePath'] = ApiClient.convertToType(data['merklePath'], [MerklePathItem]);
            }
        }
        return obj;
    }


}

/**
 * The path is the complementary data needed to calculate the merkle root.
 * @member {Array.<module:model/MerklePathItem>} merklePath
 */
MerkleProofInfoPayload.prototype['merklePath'] = undefined;






export default MerkleProofInfoPayload;

