/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
/**
* Enum class MessageTypeEnum.
* @enum {}
* @readonly
*/
export default class MessageTypeEnum {
    
        /**
         * value: 0
         * @const
         */
        "0" = 0;

    

    /**
    * Returns a <code>MessageTypeEnum</code> enum value from a Javascript object name.
    * @param {Object} data The plain JavaScript object containing the name of the enum value.
    * @return {module:model/MessageTypeEnum} The enum <code>MessageTypeEnum</code> value.
    */
    static constructFromObject(object) {
        return object;
    }
}

