/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessageTypeEnum from './MessageTypeEnum';

/**
 * The MessageDTO model module.
 * @module model/MessageDTO
 * @version 0.7.15
 */
class MessageDTO {
    /**
     * Constructs a new <code>MessageDTO</code>.
     * @alias module:model/MessageDTO
     * @param type {module:model/MessageTypeEnum} 
     * @param payload {String} The message content in hexadecimal.
     */
    constructor(type, payload) { 
        
        MessageDTO.initialize(this, type, payload);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, type, payload) { 
        obj['type'] = type;
        obj['payload'] = payload;
    }

    /**
     * Constructs a <code>MessageDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MessageDTO} obj Optional instance to populate.
     * @return {module:model/MessageDTO} The populated <code>MessageDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MessageDTO();

            if (data.hasOwnProperty('type')) {
                obj['type'] = MessageTypeEnum.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('payload')) {
                obj['payload'] = ApiClient.convertToType(data['payload'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/MessageTypeEnum} type
 */
MessageDTO.prototype['type'] = undefined;

/**
 * The message content in hexadecimal.
 * @member {String} payload
 */
MessageDTO.prototype['payload'] = undefined;






export default MessageDTO;

