/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import CosignatoryModificationDTO from './CosignatoryModificationDTO';
import ModifyMultisigAccountTransactionBodyDTO from './ModifyMultisigAccountTransactionBodyDTO';
import TransactionDTO from './TransactionDTO';

/**
 * The ModifyMultisigAccountTransactionDTO model module.
 * @module model/ModifyMultisigAccountTransactionDTO
 * @version 0.7.15
 */
class ModifyMultisigAccountTransactionDTO {
    /**
     * Constructs a new <code>ModifyMultisigAccountTransactionDTO</code>.
     * Transaction that creates or modifies a multisig account.
     * @alias module:model/ModifyMultisigAccountTransactionDTO
     * @implements module:model/TransactionDTO
     * @implements module:model/ModifyMultisigAccountTransactionBodyDTO
     */
    constructor() { 
        TransactionDTO.initialize(this);ModifyMultisigAccountTransactionBodyDTO.initialize(this, minRemovalDelta, minApprovalDelta, modifications);
        ModifyMultisigAccountTransactionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['signature'] = signature;
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
        obj['max_fee'] = maxFee;
        obj['deadline'] = deadline;
        obj['minRemovalDelta'] = minRemovalDelta;
        obj['minApprovalDelta'] = minApprovalDelta;
        obj['modifications'] = modifications;
    }

    /**
     * Constructs a <code>ModifyMultisigAccountTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ModifyMultisigAccountTransactionDTO} obj Optional instance to populate.
     * @return {module:model/ModifyMultisigAccountTransactionDTO} The populated <code>ModifyMultisigAccountTransactionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModifyMultisigAccountTransactionDTO();
            TransactionDTO.constructFromObject(data, obj);
            ModifyMultisigAccountTransactionBodyDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('max_fee')) {
                obj['max_fee'] = ApiClient.convertToType(data['max_fee'], ['Number']);
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
            if (data.hasOwnProperty('minRemovalDelta')) {
                obj['minRemovalDelta'] = ApiClient.convertToType(data['minRemovalDelta'], 'Number');
            }
            if (data.hasOwnProperty('minApprovalDelta')) {
                obj['minApprovalDelta'] = ApiClient.convertToType(data['minApprovalDelta'], 'Number');
            }
            if (data.hasOwnProperty('modifications')) {
                obj['modifications'] = ApiClient.convertToType(data['modifications'], [CosignatoryModificationDTO]);
            }
        }
        return obj;
    }


}

/**
 * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
 * @member {String} signature
 */
ModifyMultisigAccountTransactionDTO.prototype['signature'] = undefined;

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
ModifyMultisigAccountTransactionDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
ModifyMultisigAccountTransactionDTO.prototype['version'] = undefined;

/**
 * @member {Object} type
 */
ModifyMultisigAccountTransactionDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} max_fee
 */
ModifyMultisigAccountTransactionDTO.prototype['max_fee'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
ModifyMultisigAccountTransactionDTO.prototype['deadline'] = undefined;

/**
 * The number of signatures needed to remove a cosignatory. If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories. 
 * @member {Number} minRemovalDelta
 */
ModifyMultisigAccountTransactionDTO.prototype['minRemovalDelta'] = undefined;

/**
 * The number of signatures needed to approve a transaction. If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories. 
 * @member {Number} minApprovalDelta
 */
ModifyMultisigAccountTransactionDTO.prototype['minApprovalDelta'] = undefined;

/**
 * The array of cosignatory accounts to add or delete.
 * @member {Array.<module:model/CosignatoryModificationDTO>} modifications
 */
ModifyMultisigAccountTransactionDTO.prototype['modifications'] = undefined;


// Implement TransactionDTO interface:
// Implement ModifyMultisigAccountTransactionBodyDTO interface:
/**
 * @member {Object} type
 */
ModifyMultisigAccountTransactionBodyDTO.prototype['type'] = undefined;
/**
 * The number of signatures needed to remove a cosignatory. If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories. 
 * @member {Number} minRemovalDelta
 */
ModifyMultisigAccountTransactionBodyDTO.prototype['minRemovalDelta'] = undefined;
/**
 * The number of signatures needed to approve a transaction. If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories. 
 * @member {Number} minApprovalDelta
 */
ModifyMultisigAccountTransactionBodyDTO.prototype['minApprovalDelta'] = undefined;
/**
 * The array of cosignatory accounts to add or delete.
 * @member {Array.<module:model/CosignatoryModificationDTO>} modifications
 */
ModifyMultisigAccountTransactionBodyDTO.prototype['modifications'] = undefined;




export default ModifyMultisigAccountTransactionDTO;

