/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import CosignatoryModificationDTO from './CosignatoryModificationDTO';
import EntityTypeEnum from './EntityTypeEnum';
import ModifyMultisigAccountTransactionBodyDTO from './ModifyMultisigAccountTransactionBodyDTO';
import NetworkTypeEnum from './NetworkTypeEnum';
import TransactionDTO from './TransactionDTO';
import UInt64DTO from './UInt64DTO';





/**
* The ModifyMultisigAccountTransactionDTO model module.
* @module model/ModifyMultisigAccountTransactionDTO
* @version 0.7.15
*/
export default class ModifyMultisigAccountTransactionDTO {
    /**
    * Constructs a new <code>ModifyMultisigAccountTransactionDTO</code>.
    * Transaction that creates or modifies a multisig account.
    * @alias module:model/ModifyMultisigAccountTransactionDTO
    * @class
    * @implements module:model/TransactionDTO
    * @implements module:model/ModifyMultisigAccountTransactionBodyDTO
    * @param signature {String} The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    * @param signer {String} The public key of the entity signer formatted as hexadecimal.
    * @param version {module:model/NetworkTypeEnum} 
    * @param type {module:model/EntityTypeEnum} 
    * @param maxFee {module:model/UInt64DTO} 
    * @param deadline {module:model/UInt64DTO} 
    * @param minRemovalDelta {Number} The number of signatures needed to remove a cosignatory. If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories. 
    * @param minApprovalDelta {Number} The number of signatures needed to approve a transaction. If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories. 
    * @param modifications {Array.<module:model/CosignatoryModificationDTO>} The array of cosignatory accounts to add or delete.
    */

    constructor(signature, signer, version, type, maxFee, deadline, minRemovalDelta, minApprovalDelta, modifications) {
        



        

        
    }

    /**
    * Constructs a <code>ModifyMultisigAccountTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/ModifyMultisigAccountTransactionDTO} obj Optional instance to populate.
    * @return {module:model/ModifyMultisigAccountTransactionDTO} The populated <code>ModifyMultisigAccountTransactionDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ModifyMultisigAccountTransactionDTO();

            
            
            TransactionDTO.constructFromObject(data, obj);ModifyMultisigAccountTransactionBodyDTO.constructFromObject(data, obj);

        }
        return obj;
    }



    // Implement TransactionDTO interface:
    /**
    * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    * @member {String} signature
    */
    signature = undefined;
/**
    * The public key of the entity signer formatted as hexadecimal.
    * @member {String} signer
    */
    signer = undefined;
/**
    * @member {module:model/NetworkTypeEnum} version
    */
    version = undefined;
/**
    * @member {module:model/EntityTypeEnum} type
    */
    type = undefined;
/**
    * @member {module:model/UInt64DTO} max_fee
    */
    max_fee = undefined;
/**
    * @member {module:model/UInt64DTO} deadline
    */
    deadline = undefined;

    // Implement ModifyMultisigAccountTransactionBodyDTO interface:
    /**
    * The number of signatures needed to remove a cosignatory. If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories. 
    * @member {Number} minRemovalDelta
    */
    minRemovalDelta = undefined;
/**
    * The number of signatures needed to approve a transaction. If we are modifying an existing multisig account, this indicates the relative change of the minimum cosignatories. 
    * @member {Number} minApprovalDelta
    */
    minApprovalDelta = undefined;
/**
    * The array of cosignatory accounts to add or delete.
    * @member {Array.<module:model/CosignatoryModificationDTO>} modifications
    */
    modifications = undefined;







}


