/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The MosaicPropertyDTO model module.
 * @module model/MosaicPropertyDTO
 * @version 0.7.15
 */
class MosaicPropertyDTO {
    /**
     * Constructs a new <code>MosaicPropertyDTO</code>.
     * @alias module:model/MosaicPropertyDTO
     */
    constructor() { 
        
        MosaicPropertyDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>MosaicPropertyDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MosaicPropertyDTO} obj Optional instance to populate.
     * @return {module:model/MosaicPropertyDTO} The populated <code>MosaicPropertyDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MosaicPropertyDTO();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'Number');
            }
            if (data.hasOwnProperty('value')) {
                obj['value'] = ApiClient.convertToType(data['value'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * The array of mosaic properties: * 0 - MosaicFlags * 1 - Divisibility * 2 - Duration 
 * @member {Number} id
 */
MosaicPropertyDTO.prototype['id'] = undefined;

/**
 * @member {Array.<Number>} value
 */
MosaicPropertyDTO.prototype['value'] = undefined;






export default MosaicPropertyDTO;

