/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import AliasActionEnum from './AliasActionEnum';
import MosaicAliasTransactionBodyDTO from './MosaicAliasTransactionBodyDTO';
import TransactionDTO from './TransactionDTO';

/**
 * The MosaicAliasTransactionDTO model module.
 * @module model/MosaicAliasTransactionDTO
 * @version 0.7.15
 */
class MosaicAliasTransactionDTO {
    /**
     * Constructs a new <code>MosaicAliasTransactionDTO</code>.
     * Transaction that attaches a namespace to a mosaic.
     * @alias module:model/MosaicAliasTransactionDTO
     * @implements module:model/TransactionDTO
     * @implements module:model/MosaicAliasTransactionBodyDTO
     */
    constructor() { 
        TransactionDTO.initialize(this);MosaicAliasTransactionBodyDTO.initialize(this, aliasAction, namespaceId);
        MosaicAliasTransactionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['signature'] = signature;
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
        obj['max_fee'] = maxFee;
        obj['deadline'] = deadline;
        obj['aliasAction'] = aliasAction;
        obj['namespaceId'] = namespaceId;
    }

    /**
     * Constructs a <code>MosaicAliasTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MosaicAliasTransactionDTO} obj Optional instance to populate.
     * @return {module:model/MosaicAliasTransactionDTO} The populated <code>MosaicAliasTransactionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MosaicAliasTransactionDTO();
            TransactionDTO.constructFromObject(data, obj);
            MosaicAliasTransactionBodyDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('max_fee')) {
                obj['max_fee'] = ApiClient.convertToType(data['max_fee'], ['Number']);
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
            if (data.hasOwnProperty('aliasAction')) {
                obj['aliasAction'] = AliasActionEnum.constructFromObject(data['aliasAction']);
            }
            if (data.hasOwnProperty('namespaceId')) {
                obj['namespaceId'] = ApiClient.convertToType(data['namespaceId'], ['Number']);
            }
            if (data.hasOwnProperty('address')) {
                obj['address'] = ApiClient.convertToType(data['address'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
 * @member {String} signature
 */
MosaicAliasTransactionDTO.prototype['signature'] = undefined;

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
MosaicAliasTransactionDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
MosaicAliasTransactionDTO.prototype['version'] = undefined;

/**
 * @member {Object} type
 */
MosaicAliasTransactionDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} max_fee
 */
MosaicAliasTransactionDTO.prototype['max_fee'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
MosaicAliasTransactionDTO.prototype['deadline'] = undefined;

/**
 * @member {module:model/AliasActionEnum} aliasAction
 */
MosaicAliasTransactionDTO.prototype['aliasAction'] = undefined;

/**
 * @member {Array.<Number>} namespaceId
 */
MosaicAliasTransactionDTO.prototype['namespaceId'] = undefined;

/**
 * @member {Array.<Number>} address
 */
MosaicAliasTransactionDTO.prototype['address'] = undefined;


// Implement TransactionDTO interface:
// Implement MosaicAliasTransactionBodyDTO interface:
/**
 * @member {Object} type
 */
MosaicAliasTransactionBodyDTO.prototype['type'] = undefined;
/**
 * @member {module:model/AliasActionEnum} aliasAction
 */
MosaicAliasTransactionBodyDTO.prototype['aliasAction'] = undefined;
/**
 * @member {Array.<Number>} namespaceId
 */
MosaicAliasTransactionBodyDTO.prototype['namespaceId'] = undefined;
/**
 * @member {Array.<Number>} address
 */
MosaicAliasTransactionBodyDTO.prototype['address'] = undefined;




export default MosaicAliasTransactionDTO;

