/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MosaicPropertyDTO from './MosaicPropertyDTO';

/**
 * The MosaicDefinitionTransactionBodyDTO model module.
 * @module model/MosaicDefinitionTransactionBodyDTO
 * @version 0.7.15
 */
class MosaicDefinitionTransactionBodyDTO {
    /**
     * Constructs a new <code>MosaicDefinitionTransactionBodyDTO</code>.
     * @alias module:model/MosaicDefinitionTransactionBodyDTO
     * @param mosaicNonce {Number} Random nonce used to generate the mosaic id.
     * @param mosaicId {Array.<Number>} 
     * @param properties {Array.<module:model/MosaicPropertyDTO>} 
     */
    constructor(mosaicNonce, mosaicId, properties) { 
        
        MosaicDefinitionTransactionBodyDTO.initialize(this, mosaicNonce, mosaicId, properties);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, mosaicNonce, mosaicId, properties) { 
        obj['mosaicNonce'] = mosaicNonce;
        obj['mosaicId'] = mosaicId;
        obj['properties'] = properties;
    }

    /**
     * Constructs a <code>MosaicDefinitionTransactionBodyDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MosaicDefinitionTransactionBodyDTO} obj Optional instance to populate.
     * @return {module:model/MosaicDefinitionTransactionBodyDTO} The populated <code>MosaicDefinitionTransactionBodyDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MosaicDefinitionTransactionBodyDTO();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('mosaicNonce')) {
                obj['mosaicNonce'] = ApiClient.convertToType(data['mosaicNonce'], 'Number');
            }
            if (data.hasOwnProperty('mosaicId')) {
                obj['mosaicId'] = ApiClient.convertToType(data['mosaicId'], ['Number']);
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [MosaicPropertyDTO]);
            }
        }
        return obj;
    }


}

/**
 * @member {Object} type
 */
MosaicDefinitionTransactionBodyDTO.prototype['type'] = undefined;

/**
 * Random nonce used to generate the mosaic id.
 * @member {Number} mosaicNonce
 */
MosaicDefinitionTransactionBodyDTO.prototype['mosaicNonce'] = undefined;

/**
 * @member {Array.<Number>} mosaicId
 */
MosaicDefinitionTransactionBodyDTO.prototype['mosaicId'] = undefined;

/**
 * @member {Array.<module:model/MosaicPropertyDTO>} properties
 */
MosaicDefinitionTransactionBodyDTO.prototype['properties'] = undefined;






export default MosaicDefinitionTransactionBodyDTO;

