/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MosaicDefinitionDTO from './MosaicDefinitionDTO';
import MosaicMetaDTO from './MosaicMetaDTO';

/**
* The MosaicInfoDTO model module.
* @module model/MosaicInfoDTO
* @version 0.7.15
*/
export default class MosaicInfoDTO {
    /**
     * Constructs a new <code>MosaicInfoDTO</code>.
     * @alias module:model/MosaicInfoDTO
     * @param meta {module:model/MosaicMetaDTO} 
     * @param mosaic {module:model/MosaicDefinitionDTO} 
     */
    constructor(meta, mosaic) { 
        
        MosaicInfoDTO.initialize(this, meta, mosaic);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, meta, mosaic) { 
        obj['meta'] = meta;
        obj['mosaic'] = mosaic;
    }

    /**
     * Constructs a <code>MosaicInfoDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MosaicInfoDTO} obj Optional instance to populate.
     * @return {module:model/MosaicInfoDTO} The populated <code>MosaicInfoDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MosaicInfoDTO();

            if (data.hasOwnProperty('meta')) {
                obj['meta'] = MosaicMetaDTO.constructFromObject(data['meta']);
            }
            if (data.hasOwnProperty('mosaic')) {
                obj['mosaic'] = MosaicDefinitionDTO.constructFromObject(data['mosaic']);
            }
        }
        return obj;
    }


}

/**
 * @member {module:model/MosaicMetaDTO} meta
 */
MosaicInfoDTO.prototype['meta'] = undefined;

/**
 * @member {module:model/MosaicDefinitionDTO} mosaic
 */
MosaicInfoDTO.prototype['mosaic'] = undefined;






export default MosaicInfoDTO;

