/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import MosaicPropertyDTO from './MosaicPropertyDTO';
import UInt64DTO from './UInt64DTO';





/**
* The MosaicDefinitionTransactionBodyDTO model module.
* @module model/MosaicDefinitionTransactionBodyDTO
* @version 0.7.15
*/
export default class MosaicDefinitionTransactionBodyDTO {
    /**
    * Constructs a new <code>MosaicDefinitionTransactionBodyDTO</code>.
    * @alias module:model/MosaicDefinitionTransactionBodyDTO
    * @class
    * @param mosaicNonce {Number} Random nonce used to generate the mosaic id.
    * @param mosaicId {module:model/UInt64DTO} 
    * @param properties {Array.<module:model/MosaicPropertyDTO>} 
    */

    constructor(mosaicNonce, mosaicId, properties) {
        



        this['mosaicNonce'] = mosaicNonce;this['mosaicId'] = mosaicId;this['properties'] = properties;

        
    }

    /**
    * Constructs a <code>MosaicDefinitionTransactionBodyDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/MosaicDefinitionTransactionBodyDTO} obj Optional instance to populate.
    * @return {module:model/MosaicDefinitionTransactionBodyDTO} The populated <code>MosaicDefinitionTransactionBodyDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MosaicDefinitionTransactionBodyDTO();

            
            
            

            if (data.hasOwnProperty('mosaicNonce')) {
                obj['mosaicNonce'] = ApiClient.convertToType(data['mosaicNonce'], 'Number');
            }
            if (data.hasOwnProperty('mosaicId')) {
                obj['mosaicId'] = UInt64DTO.constructFromObject(data['mosaicId']);
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [MosaicPropertyDTO]);
            }
        }
        return obj;
    }

    /**
    * Random nonce used to generate the mosaic id.
    * @member {Number} mosaicNonce
    */
    mosaicNonce = undefined;
    /**
    * @member {module:model/UInt64DTO} mosaicId
    */
    mosaicId = undefined;
    /**
    * @member {Array.<module:model/MosaicPropertyDTO>} properties
    */
    properties = undefined;








}


