/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The MosaicNameDTO model module.
* @module model/MosaicNameDTO
* @version 0.7.15
*/
export default class MosaicNameDTO {
    /**
    * Constructs a new <code>MosaicNameDTO</code>.
    * @alias module:model/MosaicNameDTO
    * @class
    * @param mosaicId {module:model/UInt64DTO} 
    * @param names {Array.<String>} The mosaic linked namespace names.
    */

    constructor(mosaicId, names) {
        
        MosaicNameDTO.initialize(this, mosaicId, names);
    }

        
        

        this['mosaicId'] = mosaicId;this['names'] = names;

        
    }

    /**
     * Constructs a <code>MosaicNameDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MosaicNameDTO} obj Optional instance to populate.
     * @return {module:model/MosaicNameDTO} The populated <code>MosaicNameDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MosaicNameDTO();

            
            
            

            if (data.hasOwnProperty('mosaicId')) {
                obj['mosaicId'] = ApiClient.convertToType(data['mosaicId'], ['Number']);
            }
            if (data.hasOwnProperty('names')) {
                obj['names'] = ApiClient.convertToType(data['names'], ['String']);
            }
        }
        return obj;
    }

    /**
    * @member {module:model/UInt64DTO} mosaicId
    */
    mosaicId = undefined;
    /**
    * The mosaic linked namespace names.
    * @member {Array.<String>} names
    */
    names = undefined;

}

/**
 * @member {Array.<Number>} mosaicId
 */
MosaicNameDTO.prototype['mosaicId'] = undefined;

/**
 * The mosaic linked namespace names.
 * @member {Array.<String>} names
 */
MosaicNameDTO.prototype['names'] = undefined;






export default MosaicNameDTO;

