/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The MosaicDTO model module.
* @module model/MosaicDTO
* @version 0.7.15
*/
export default class MosaicDTO {
    /**
     * Constructs a new <code>MosaicDTO</code>.
     * @alias module:model/MosaicDTO
     * @param id {Array.<Number>} 
     * @param amount {Array.<Number>} 
     */
    constructor(id, amount) { 
        
        MosaicDTO.initialize(this, id, amount);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, id, amount) { 
        obj['id'] = id;
        obj['amount'] = amount;
    }

    /**
     * Constructs a <code>MosaicDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MosaicDTO} obj Optional instance to populate.
     * @return {module:model/MosaicDTO} The populated <code>MosaicDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MosaicDTO();

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], ['Number']);
            }
            if (data.hasOwnProperty('amount')) {
                obj['amount'] = ApiClient.convertToType(data['amount'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} id
 */
MosaicDTO.prototype['id'] = undefined;

/**
 * @member {Array.<Number>} amount
 */
MosaicDTO.prototype['amount'] = undefined;






export default MosaicDTO;

