/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MosaicDefinitionTransactionBodyDTO from './MosaicDefinitionTransactionBodyDTO';
import MosaicPropertyDTO from './MosaicPropertyDTO';
import TransactionDTO from './TransactionDTO';

/**
 * The MosaicDefinitionTransactionDTO model module.
 * @module model/MosaicDefinitionTransactionDTO
 * @version 0.7.15
 */
class MosaicDefinitionTransactionDTO {
    /**
     * Constructs a new <code>MosaicDefinitionTransactionDTO</code>.
     * Transaction that creates a new mosaic.
     * @alias module:model/MosaicDefinitionTransactionDTO
     * @implements module:model/TransactionDTO
     * @implements module:model/MosaicDefinitionTransactionBodyDTO
     */
    constructor() { 
        TransactionDTO.initialize(this);MosaicDefinitionTransactionBodyDTO.initialize(this, mosaicNonce, mosaicId, properties);
        MosaicDefinitionTransactionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['signature'] = signature;
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
        obj['max_fee'] = maxFee;
        obj['deadline'] = deadline;
        obj['mosaicNonce'] = mosaicNonce;
        obj['mosaicId'] = mosaicId;
        obj['properties'] = properties;
    }

    /**
     * Constructs a <code>MosaicDefinitionTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MosaicDefinitionTransactionDTO} obj Optional instance to populate.
     * @return {module:model/MosaicDefinitionTransactionDTO} The populated <code>MosaicDefinitionTransactionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MosaicDefinitionTransactionDTO();
            TransactionDTO.constructFromObject(data, obj);
            MosaicDefinitionTransactionBodyDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('max_fee')) {
                obj['max_fee'] = ApiClient.convertToType(data['max_fee'], ['Number']);
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
            if (data.hasOwnProperty('mosaicNonce')) {
                obj['mosaicNonce'] = ApiClient.convertToType(data['mosaicNonce'], 'Number');
            }
            if (data.hasOwnProperty('mosaicId')) {
                obj['mosaicId'] = ApiClient.convertToType(data['mosaicId'], ['Number']);
            }
            if (data.hasOwnProperty('properties')) {
                obj['properties'] = ApiClient.convertToType(data['properties'], [MosaicPropertyDTO]);
            }
        }
        return obj;
    }


}

/**
 * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
 * @member {String} signature
 */
MosaicDefinitionTransactionDTO.prototype['signature'] = undefined;

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
MosaicDefinitionTransactionDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
MosaicDefinitionTransactionDTO.prototype['version'] = undefined;

/**
 * @member {Object} type
 */
MosaicDefinitionTransactionDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} max_fee
 */
MosaicDefinitionTransactionDTO.prototype['max_fee'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
MosaicDefinitionTransactionDTO.prototype['deadline'] = undefined;

/**
 * Random nonce used to generate the mosaic id.
 * @member {Number} mosaicNonce
 */
MosaicDefinitionTransactionDTO.prototype['mosaicNonce'] = undefined;

/**
 * @member {Array.<Number>} mosaicId
 */
MosaicDefinitionTransactionDTO.prototype['mosaicId'] = undefined;

/**
 * @member {Array.<module:model/MosaicPropertyDTO>} properties
 */
MosaicDefinitionTransactionDTO.prototype['properties'] = undefined;


// Implement TransactionDTO interface:
// Implement MosaicDefinitionTransactionBodyDTO interface:
/**
 * @member {Object} type
 */
MosaicDefinitionTransactionBodyDTO.prototype['type'] = undefined;
/**
 * Random nonce used to generate the mosaic id.
 * @member {Number} mosaicNonce
 */
MosaicDefinitionTransactionBodyDTO.prototype['mosaicNonce'] = undefined;
/**
 * @member {Array.<Number>} mosaicId
 */
MosaicDefinitionTransactionBodyDTO.prototype['mosaicId'] = undefined;
/**
 * @member {Array.<module:model/MosaicPropertyDTO>} properties
 */
MosaicDefinitionTransactionBodyDTO.prototype['properties'] = undefined;




export default MosaicDefinitionTransactionDTO;

