/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MultisigAccountInfoDTO from './MultisigAccountInfoDTO';

/**
 * The MultisigAccountGraphInfoDTO model module.
 * @module model/MultisigAccountGraphInfoDTO
 * @version 0.7.15
 */
class MultisigAccountGraphInfoDTO {
    /**
     * Constructs a new <code>MultisigAccountGraphInfoDTO</code>.
     * @alias module:model/MultisigAccountGraphInfoDTO
     * @param level {Number} The level of the multisig account.
     * @param multisigEntries {Array.<module:model/MultisigAccountInfoDTO>} The array of multisig accounts for this level.
     */
    constructor(level, multisigEntries) { 
        
        MultisigAccountGraphInfoDTO.initialize(this, level, multisigEntries);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, level, multisigEntries) { 
        obj['level'] = level;
        obj['multisigEntries'] = multisigEntries;
    }

    /**
     * Constructs a <code>MultisigAccountGraphInfoDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/MultisigAccountGraphInfoDTO} obj Optional instance to populate.
     * @return {module:model/MultisigAccountGraphInfoDTO} The populated <code>MultisigAccountGraphInfoDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new MultisigAccountGraphInfoDTO();

            if (data.hasOwnProperty('level')) {
                obj['level'] = ApiClient.convertToType(data['level'], 'Number');
            }
            if (data.hasOwnProperty('multisigEntries')) {
                obj['multisigEntries'] = ApiClient.convertToType(data['multisigEntries'], [MultisigAccountInfoDTO]);
            }
        }
        return obj;
    }


}

/**
 * The level of the multisig account.
 * @member {Number} level
 */
MultisigAccountGraphInfoDTO.prototype['level'] = undefined;

/**
 * The array of multisig accounts for this level.
 * @member {Array.<module:model/MultisigAccountInfoDTO>} multisigEntries
 */
MultisigAccountGraphInfoDTO.prototype['multisigEntries'] = undefined;






export default MultisigAccountGraphInfoDTO;

