/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The NamespaceIds model module.
* @module model/NamespaceIds
* @version 0.7.15
*/
export default class NamespaceIds {
    /**
     * Constructs a new <code>NamespaceIds</code>.
     * @alias module:model/NamespaceIds
     */
    constructor() { 
        
        NamespaceIds.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>NamespaceIds</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NamespaceIds} obj Optional instance to populate.
     * @return {module:model/NamespaceIds} The populated <code>NamespaceIds</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NamespaceIds();

            if (data.hasOwnProperty('namespaceIds')) {
                obj['namespaceIds'] = ApiClient.convertToType(data['namespaceIds'], ['String']);
            }
        }
        return obj;
    }

    /**
    * The array of namespace identifiers.
    * @member {Array.<String>} namespaceIds
    */
    namespaceIds = undefined;


}

/**
 * The array of namespace identifiers.
 * @member {Array.<String>} namespaceIds
 */
NamespaceIds.prototype['namespaceIds'] = undefined;






export default NamespaceIds;

