/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The NamespaceMetaDTO model module.
* @module model/NamespaceMetaDTO
* @version 0.7.15
*/
export default class NamespaceMetaDTO {
    /**
    * Constructs a new <code>NamespaceMetaDTO</code>.
    * @alias module:model/NamespaceMetaDTO
    * @class
    * @param id {String} 
    * @param active {Boolean} 
    * @param index {Number} 
    */

    constructor(id, active, index) {
        



        this['id'] = id;this['active'] = active;this['index'] = index;

        
    }

    /**
    * Constructs a <code>NamespaceMetaDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/NamespaceMetaDTO} obj Optional instance to populate.
    * @return {module:model/NamespaceMetaDTO} The populated <code>NamespaceMetaDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NamespaceMetaDTO();

            
            
            

            if (data.hasOwnProperty('id')) {
                obj['id'] = ApiClient.convertToType(data['id'], 'String');
            }
            if (data.hasOwnProperty('active')) {
                obj['active'] = ApiClient.convertToType(data['active'], 'Boolean');
            }
            if (data.hasOwnProperty('index')) {
                obj['index'] = ApiClient.convertToType(data['index'], 'Number');
            }
        }
        return obj;
    }

    /**
    * @member {String} id
    */
    id = undefined;
    /**
    * @member {Boolean} active
    */
    active = undefined;
    /**
    * @member {Number} index
    */
    index = undefined;








}


