/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The NetworkTypeDTO model module.
 * @module model/NetworkTypeDTO
 * @version 0.7.15
 */
class NetworkTypeDTO {
    /**
     * Constructs a new <code>NetworkTypeDTO</code>.
     * @alias module:model/NetworkTypeDTO
     * @param name {String} The name of the network.
     * @param description {String} A short text describing the network.
     */
    constructor(name, description) { 
        
        NetworkTypeDTO.initialize(this, name, description);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, name, description) { 
        obj['name'] = name;
        obj['description'] = description;
    }

    /**
     * Constructs a <code>NetworkTypeDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/NetworkTypeDTO} obj Optional instance to populate.
     * @return {module:model/NetworkTypeDTO} The populated <code>NetworkTypeDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new NetworkTypeDTO();

            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
            if (data.hasOwnProperty('description')) {
                obj['description'] = ApiClient.convertToType(data['description'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The name of the network.
 * @member {String} name
 */
NetworkTypeDTO.prototype['name'] = undefined;

/**
 * A short text describing the network.
 * @member {String} description
 */
NetworkTypeDTO.prototype['description'] = undefined;






export default NetworkTypeDTO;

