/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The ReceiptDTO model module.
 * @module model/ReceiptDTO
 * @version 0.7.15
 */
class ReceiptDTO {
    /**
     * Constructs a new <code>ReceiptDTO</code>.
     * @alias module:model/ReceiptDTO
     * @param version {Number} The version of the receipt.
     * @param type {module:model/ReceiptDTO} 
     */
    constructor(version, type) { 
        
        ReceiptDTO.initialize(this, version, type);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, version, type) { 
        obj['version'] = version;
        obj['type'] = type;
    }

    /**
     * Constructs a <code>ReceiptDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/ReceiptDTO} obj Optional instance to populate.
     * @return {module:model/ReceiptDTO} The populated <code>ReceiptDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new ReceiptDTO();

            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ReceiptDTO.constructFromObject(data['type']);
            }
        }
        return obj;
    }


}

/**
 * The version of the receipt.
 * @member {Number} version
 */
ReceiptDTO.prototype['version'] = undefined;

/**
 * @member {module:model/ReceiptDTO} type
 */
ReceiptDTO.prototype['type'] = undefined;






export default ReceiptDTO;

