/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NamespaceTypeEnum from './NamespaceTypeEnum';
import RegisterNamespaceTransactionBodyDTO from './RegisterNamespaceTransactionBodyDTO';
import TransactionDTO from './TransactionDTO';

/**
 * The RegisterNamespaceTransactionDTO model module.
 * @module model/RegisterNamespaceTransactionDTO
 * @version 0.7.15
 */
class RegisterNamespaceTransactionDTO {
    /**
     * Constructs a new <code>RegisterNamespaceTransactionDTO</code>.
     * Transaction that creates or renew a namespace.
     * @alias module:model/RegisterNamespaceTransactionDTO
     * @implements module:model/TransactionDTO
     * @implements module:model/RegisterNamespaceTransactionBodyDTO
     */
    constructor() { 
        TransactionDTO.initialize(this);RegisterNamespaceTransactionBodyDTO.initialize(this, namespaceType, duration, namespaceId, name);
        RegisterNamespaceTransactionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['signature'] = signature;
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
        obj['max_fee'] = maxFee;
        obj['deadline'] = deadline;
        obj['namespaceType'] = namespaceType;
        obj['duration'] = duration;
        obj['namespaceId'] = namespaceId;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>RegisterNamespaceTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegisterNamespaceTransactionDTO} obj Optional instance to populate.
     * @return {module:model/RegisterNamespaceTransactionDTO} The populated <code>RegisterNamespaceTransactionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegisterNamespaceTransactionDTO();
            TransactionDTO.constructFromObject(data, obj);
            RegisterNamespaceTransactionBodyDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('max_fee')) {
                obj['max_fee'] = ApiClient.convertToType(data['max_fee'], ['Number']);
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
            if (data.hasOwnProperty('namespaceType')) {
                obj['namespaceType'] = NamespaceTypeEnum.constructFromObject(data['namespaceType']);
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], ['Number']);
            }
            if (data.hasOwnProperty('namespaceId')) {
                obj['namespaceId'] = ApiClient.convertToType(data['namespaceId'], ['Number']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
 * @member {String} signature
 */
RegisterNamespaceTransactionDTO.prototype['signature'] = undefined;

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
RegisterNamespaceTransactionDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
RegisterNamespaceTransactionDTO.prototype['version'] = undefined;

/**
 * @member {Object} type
 */
RegisterNamespaceTransactionDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} max_fee
 */
RegisterNamespaceTransactionDTO.prototype['max_fee'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
RegisterNamespaceTransactionDTO.prototype['deadline'] = undefined;

/**
 * @member {module:model/NamespaceTypeEnum} namespaceType
 */
RegisterNamespaceTransactionDTO.prototype['namespaceType'] = undefined;

/**
 * @member {Array.<Number>} duration
 */
RegisterNamespaceTransactionDTO.prototype['duration'] = undefined;

/**
 * @member {Array.<Number>} namespaceId
 */
RegisterNamespaceTransactionDTO.prototype['namespaceId'] = undefined;

/**
 * The unique namespace name.
 * @member {String} name
 */
RegisterNamespaceTransactionDTO.prototype['name'] = undefined;


// Implement TransactionDTO interface:
// Implement RegisterNamespaceTransactionBodyDTO interface:
/**
 * @member {Object} type
 */
RegisterNamespaceTransactionBodyDTO.prototype['type'] = undefined;
/**
 * @member {module:model/NamespaceTypeEnum} namespaceType
 */
RegisterNamespaceTransactionBodyDTO.prototype['namespaceType'] = undefined;
/**
 * @member {Array.<Number>} duration
 */
RegisterNamespaceTransactionBodyDTO.prototype['duration'] = undefined;
/**
 * @member {Array.<Number>} namespaceId
 */
RegisterNamespaceTransactionBodyDTO.prototype['namespaceId'] = undefined;
/**
 * The unique namespace name.
 * @member {String} name
 */
RegisterNamespaceTransactionBodyDTO.prototype['name'] = undefined;




export default RegisterNamespaceTransactionDTO;

