/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import NamespaceTypeEnum from './NamespaceTypeEnum';

/**
 * The RegisterNamespaceTransactionBodyDTO model module.
 * @module model/RegisterNamespaceTransactionBodyDTO
 * @version 0.7.15
 */
class RegisterNamespaceTransactionBodyDTO {
    /**
     * Constructs a new <code>RegisterNamespaceTransactionBodyDTO</code>.
     * @alias module:model/RegisterNamespaceTransactionBodyDTO
     * @param namespaceType {module:model/NamespaceTypeEnum} 
     * @param duration {Array.<Number>} 
     * @param namespaceId {Array.<Number>} 
     * @param name {String} The unique namespace name.
     */
    constructor(namespaceType, duration, namespaceId, name) { 
        
        RegisterNamespaceTransactionBodyDTO.initialize(this, namespaceType, duration, namespaceId, name);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, namespaceType, duration, namespaceId, name) { 
        obj['namespaceType'] = namespaceType;
        obj['duration'] = duration;
        obj['namespaceId'] = namespaceId;
        obj['name'] = name;
    }

    /**
     * Constructs a <code>RegisterNamespaceTransactionBodyDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/RegisterNamespaceTransactionBodyDTO} obj Optional instance to populate.
     * @return {module:model/RegisterNamespaceTransactionBodyDTO} The populated <code>RegisterNamespaceTransactionBodyDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegisterNamespaceTransactionBodyDTO();

            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('namespaceType')) {
                obj['namespaceType'] = NamespaceTypeEnum.constructFromObject(data['namespaceType']);
            }
            if (data.hasOwnProperty('duration')) {
                obj['duration'] = ApiClient.convertToType(data['duration'], ['Number']);
            }
            if (data.hasOwnProperty('namespaceId')) {
                obj['namespaceId'] = ApiClient.convertToType(data['namespaceId'], ['Number']);
            }
            if (data.hasOwnProperty('name')) {
                obj['name'] = ApiClient.convertToType(data['name'], 'String');
            }
        }
        return obj;
    }


}

/**
 * @member {Object} type
 */
RegisterNamespaceTransactionBodyDTO.prototype['type'] = undefined;

/**
 * @member {module:model/NamespaceTypeEnum} namespaceType
 */
RegisterNamespaceTransactionBodyDTO.prototype['namespaceType'] = undefined;

/**
 * @member {Array.<Number>} duration
 */
RegisterNamespaceTransactionBodyDTO.prototype['duration'] = undefined;

/**
 * @member {Array.<Number>} namespaceId
 */
RegisterNamespaceTransactionBodyDTO.prototype['namespaceId'] = undefined;

/**
 * The unique namespace name.
 * @member {String} name
 */
RegisterNamespaceTransactionBodyDTO.prototype['name'] = undefined;






export default RegisterNamespaceTransactionBodyDTO;

