/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import EntityTypeEnum from './EntityTypeEnum';
import NamespaceTypeEnum from './NamespaceTypeEnum';
import NetworkTypeEnum from './NetworkTypeEnum';
import RegisterNamespaceTransactionBodyDTO from './RegisterNamespaceTransactionBodyDTO';
import TransactionDTO from './TransactionDTO';
import UInt64DTO from './UInt64DTO';





/**
* The RegisterNamespaceTransactionDTO model module.
* @module model/RegisterNamespaceTransactionDTO
* @version 0.7.15
*/
export default class RegisterNamespaceTransactionDTO {
    /**
    * Constructs a new <code>RegisterNamespaceTransactionDTO</code>.
    * Transaction that creates or renew a namespace.
    * @alias module:model/RegisterNamespaceTransactionDTO
    * @class
    * @implements module:model/TransactionDTO
    * @implements module:model/RegisterNamespaceTransactionBodyDTO
    * @param signature {String} The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    * @param signer {String} The public key of the entity signer formatted as hexadecimal.
    * @param version {module:model/NetworkTypeEnum} 
    * @param type {module:model/EntityTypeEnum} 
    * @param maxFee {module:model/UInt64DTO} 
    * @param deadline {module:model/UInt64DTO} 
    * @param namespaceType {module:model/NamespaceTypeEnum} 
    * @param duration {module:model/UInt64DTO} 
    * @param namespaceId {module:model/UInt64DTO} 
    * @param name {String} The unique namespace name.
    * @param parentId {module:model/UInt64DTO} 
    */

    constructor(signature, signer, version, type, maxFee, deadline, namespaceType, duration, namespaceId, name, parentId) {
        



        

        
    }

    /**
    * Constructs a <code>RegisterNamespaceTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/RegisterNamespaceTransactionDTO} obj Optional instance to populate.
    * @return {module:model/RegisterNamespaceTransactionDTO} The populated <code>RegisterNamespaceTransactionDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new RegisterNamespaceTransactionDTO();

            
            
            TransactionDTO.constructFromObject(data, obj);RegisterNamespaceTransactionBodyDTO.constructFromObject(data, obj);

        }
        return obj;
    }



    // Implement TransactionDTO interface:
    /**
    * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    * @member {String} signature
    */
    signature = undefined;
/**
    * The public key of the entity signer formatted as hexadecimal.
    * @member {String} signer
    */
    signer = undefined;
/**
    * @member {module:model/NetworkTypeEnum} version
    */
    version = undefined;
/**
    * @member {module:model/EntityTypeEnum} type
    */
    type = undefined;
/**
    * @member {module:model/UInt64DTO} max_fee
    */
    max_fee = undefined;
/**
    * @member {module:model/UInt64DTO} deadline
    */
    deadline = undefined;

    // Implement RegisterNamespaceTransactionBodyDTO interface:
    /**
    * @member {module:model/NamespaceTypeEnum} namespaceType
    */
    namespaceType = undefined;
/**
    * @member {module:model/UInt64DTO} duration
    */
    duration = undefined;
/**
    * @member {module:model/UInt64DTO} namespaceId
    */
    namespaceId = undefined;
/**
    * The unique namespace name.
    * @member {String} name
    */
    name = undefined;
/**
    * @member {module:model/UInt64DTO} parentId
    */
    parentId = undefined;







}


