/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';
import HashAlgorithmEnum from './HashAlgorithmEnum';





/**
* The SecretProofTransactionBodyDTO model module.
* @module model/SecretProofTransactionBodyDTO
* @version 0.7.15
*/
export default class SecretProofTransactionBodyDTO {
    /**
    * Constructs a new <code>SecretProofTransactionBodyDTO</code>.
    * @alias module:model/SecretProofTransactionBodyDTO
    * @class
    * @param hashAlgorithm {module:model/HashAlgorithmEnum} 
    * @param secret {String} The proof hashed.
    * @param proof {String} The original random set of bytes.
    */

    constructor(hashAlgorithm, secret, proof) {
        



        this['hashAlgorithm'] = hashAlgorithm;this['secret'] = secret;this['proof'] = proof;

        
    }

    /**
    * Constructs a <code>SecretProofTransactionBodyDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/SecretProofTransactionBodyDTO} obj Optional instance to populate.
    * @return {module:model/SecretProofTransactionBodyDTO} The populated <code>SecretProofTransactionBodyDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecretProofTransactionBodyDTO();

            
            
            

            if (data.hasOwnProperty('hashAlgorithm')) {
                obj['hashAlgorithm'] = HashAlgorithmEnum.constructFromObject(data['hashAlgorithm']);
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
            if (data.hasOwnProperty('proof')) {
                obj['proof'] = ApiClient.convertToType(data['proof'], 'String');
            }
        }
        return obj;
    }

    /**
    * @member {module:model/HashAlgorithmEnum} hashAlgorithm
    */
    hashAlgorithm = undefined;
    /**
    * The proof hashed.
    * @member {String} secret
    */
    secret = undefined;
    /**
    * The original random set of bytes.
    * @member {String} proof
    */
    proof = undefined;








}


