/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import HashAlgorithmEnum from './HashAlgorithmEnum';
import SecretProofTransactionBodyDTO from './SecretProofTransactionBodyDTO';
import TransactionDTO from './TransactionDTO';

/**
 * The SecretProofTransactionDTO model module.
 * @module model/SecretProofTransactionDTO
 * @version 0.7.15
 */
class SecretProofTransactionDTO {
    /**
     * Constructs a new <code>SecretProofTransactionDTO</code>.
     * Transaction that revealed a proof.
     * @alias module:model/SecretProofTransactionDTO
     * @implements module:model/TransactionDTO
     * @implements module:model/SecretProofTransactionBodyDTO
     */
    constructor() { 
        TransactionDTO.initialize(this);SecretProofTransactionBodyDTO.initialize(this, hashAlgorithm, secret, proof);
        SecretProofTransactionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['signature'] = signature;
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
        obj['max_fee'] = maxFee;
        obj['deadline'] = deadline;
        obj['hashAlgorithm'] = hashAlgorithm;
        obj['secret'] = secret;
        obj['proof'] = proof;
    }

    /**
     * Constructs a <code>SecretProofTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/SecretProofTransactionDTO} obj Optional instance to populate.
     * @return {module:model/SecretProofTransactionDTO} The populated <code>SecretProofTransactionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new SecretProofTransactionDTO();
            TransactionDTO.constructFromObject(data, obj);
            SecretProofTransactionBodyDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('max_fee')) {
                obj['max_fee'] = ApiClient.convertToType(data['max_fee'], ['Number']);
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
            if (data.hasOwnProperty('hashAlgorithm')) {
                obj['hashAlgorithm'] = HashAlgorithmEnum.constructFromObject(data['hashAlgorithm']);
            }
            if (data.hasOwnProperty('secret')) {
                obj['secret'] = ApiClient.convertToType(data['secret'], 'String');
            }
            if (data.hasOwnProperty('proof')) {
                obj['proof'] = ApiClient.convertToType(data['proof'], 'String');
            }
        }
        return obj;
    }


}

/**
 * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
 * @member {String} signature
 */
SecretProofTransactionDTO.prototype['signature'] = undefined;

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
SecretProofTransactionDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
SecretProofTransactionDTO.prototype['version'] = undefined;

/**
 * @member {Object} type
 */
SecretProofTransactionDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} max_fee
 */
SecretProofTransactionDTO.prototype['max_fee'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
SecretProofTransactionDTO.prototype['deadline'] = undefined;

/**
 * @member {module:model/HashAlgorithmEnum} hashAlgorithm
 */
SecretProofTransactionDTO.prototype['hashAlgorithm'] = undefined;

/**
 * The proof hashed.
 * @member {String} secret
 */
SecretProofTransactionDTO.prototype['secret'] = undefined;

/**
 * The original random set of bytes.
 * @member {String} proof
 */
SecretProofTransactionDTO.prototype['proof'] = undefined;


// Implement TransactionDTO interface:
// Implement SecretProofTransactionBodyDTO interface:
/**
 * @member {Object} type
 */
SecretProofTransactionBodyDTO.prototype['type'] = undefined;
/**
 * @member {module:model/HashAlgorithmEnum} hashAlgorithm
 */
SecretProofTransactionBodyDTO.prototype['hashAlgorithm'] = undefined;
/**
 * The proof hashed.
 * @member {String} secret
 */
SecretProofTransactionBodyDTO.prototype['secret'] = undefined;
/**
 * The original random set of bytes.
 * @member {String} proof
 */
SecretProofTransactionBodyDTO.prototype['proof'] = undefined;




export default SecretProofTransactionDTO;

