/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import EntityDTO from './EntityDTO';
import EntityTypeEnum from './EntityTypeEnum';
import TransactionBodyDTO from './TransactionBodyDTO';
import VerifiableEntityDTO from './VerifiableEntityDTO';

/**
 * The TransactionDTO model module.
 * @module model/TransactionDTO
 * @version 0.7.15
 */
class TransactionDTO {
    /**
     * Constructs a new <code>TransactionDTO</code>.
     * @alias module:model/TransactionDTO
     * @implements module:model/VerifiableEntityDTO
     * @implements module:model/EntityDTO
     * @implements module:model/TransactionBodyDTO
     */
    constructor() { 
        VerifiableEntityDTO.initialize(this, signature);EntityDTO.initialize(this, signer, version, type);TransactionBodyDTO.initialize(this, maxFee, deadline);
        TransactionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['signature'] = signature;
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
        obj['max_fee'] = maxFee;
        obj['deadline'] = deadline;
    }

    /**
     * Constructs a <code>TransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionDTO} obj Optional instance to populate.
     * @return {module:model/TransactionDTO} The populated <code>TransactionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionDTO();
            VerifiableEntityDTO.constructFromObject(data, obj);
            EntityDTO.constructFromObject(data, obj);
            TransactionBodyDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = EntityTypeEnum.constructFromObject(data['type']);
            }
            if (data.hasOwnProperty('max_fee')) {
                obj['max_fee'] = ApiClient.convertToType(data['max_fee'], ['Number']);
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
 * @member {String} signature
 */
TransactionDTO.prototype['signature'] = undefined;

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
TransactionDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
TransactionDTO.prototype['version'] = undefined;

/**
 * @member {module:model/EntityTypeEnum} type
 */
TransactionDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} max_fee
 */
TransactionDTO.prototype['max_fee'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
TransactionDTO.prototype['deadline'] = undefined;


// Implement VerifiableEntityDTO interface:
/**
 * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
 * @member {String} signature
 */
VerifiableEntityDTO.prototype['signature'] = undefined;
// Implement EntityDTO interface:
/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
EntityDTO.prototype['signer'] = undefined;
/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
EntityDTO.prototype['version'] = undefined;
/**
 * @member {module:model/EntityTypeEnum} type
 */
EntityDTO.prototype['type'] = undefined;
// Implement TransactionBodyDTO interface:
/**
 * @member {Array.<Number>} max_fee
 */
TransactionBodyDTO.prototype['max_fee'] = undefined;
/**
 * @member {Array.<Number>} deadline
 */
TransactionBodyDTO.prototype['deadline'] = undefined;




export default TransactionDTO;

