/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import ReceiptDTO from './ReceiptDTO';
import SourceDTO from './SourceDTO';

/**
 * The TransactionStatementDTO model module.
 * @module model/TransactionStatementDTO
 * @version 0.7.15
 */
class TransactionStatementDTO {
    /**
     * Constructs a new <code>TransactionStatementDTO</code>.
     * The collection of receipts related to a transaction.
     * @alias module:model/TransactionStatementDTO
     * @param height {Array.<Number>} 
     * @param source {module:model/SourceDTO} 
     * @param receipts {Array.<module:model/ReceiptDTO>} The array of receipts.
     */
    constructor(height, source, receipts) { 
        
        TransactionStatementDTO.initialize(this, height, source, receipts);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, height, source, receipts) { 
        obj['height'] = height;
        obj['source'] = source;
        obj['receipts'] = receipts;
    }

    /**
     * Constructs a <code>TransactionStatementDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionStatementDTO} obj Optional instance to populate.
     * @return {module:model/TransactionStatementDTO} The populated <code>TransactionStatementDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionStatementDTO();

            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], ['Number']);
            }
            if (data.hasOwnProperty('source')) {
                obj['source'] = SourceDTO.constructFromObject(data['source']);
            }
            if (data.hasOwnProperty('receipts')) {
                obj['receipts'] = ApiClient.convertToType(data['receipts'], [ReceiptDTO]);
            }
        }
        return obj;
    }


}

/**
 * @member {Array.<Number>} height
 */
TransactionStatementDTO.prototype['height'] = undefined;

/**
 * @member {module:model/SourceDTO} source
 */
TransactionStatementDTO.prototype['source'] = undefined;

/**
 * The array of receipts.
 * @member {Array.<module:model/ReceiptDTO>} receipts
 */
TransactionStatementDTO.prototype['receipts'] = undefined;






export default TransactionStatementDTO;

