/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';
import MessageDTO from './MessageDTO';
import MosaicDTO from './MosaicDTO';
import TransactionDTO from './TransactionDTO';
import TransferTransactionBodyDTO from './TransferTransactionBodyDTO';

/**
 * The TransferTransactionDTO model module.
 * @module model/TransferTransactionDTO
 * @version 0.7.15
 */
class TransferTransactionDTO {
    /**
     * Constructs a new <code>TransferTransactionDTO</code>.
     * Transaction that transfers mosaics and messages to another account.
     * @alias module:model/TransferTransactionDTO
     * @implements module:model/TransactionDTO
     * @implements module:model/TransferTransactionBodyDTO
     */
    constructor() { 
        TransactionDTO.initialize(this);TransferTransactionBodyDTO.initialize(this, recipient, mosaics, message);
        TransferTransactionDTO.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
        obj['signature'] = signature;
        obj['signer'] = signer;
        obj['version'] = version;
        obj['type'] = type;
        obj['max_fee'] = maxFee;
        obj['deadline'] = deadline;
        obj['recipient'] = recipient;
        obj['mosaics'] = mosaics;
        obj['message'] = message;
    }

    /**
     * Constructs a <code>TransferTransactionDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransferTransactionDTO} obj Optional instance to populate.
     * @return {module:model/TransferTransactionDTO} The populated <code>TransferTransactionDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransferTransactionDTO();
            TransactionDTO.constructFromObject(data, obj);
            TransferTransactionBodyDTO.constructFromObject(data, obj);

            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
            if (data.hasOwnProperty('signer')) {
                obj['signer'] = ApiClient.convertToType(data['signer'], 'String');
            }
            if (data.hasOwnProperty('version')) {
                obj['version'] = ApiClient.convertToType(data['version'], 'Number');
            }
            if (data.hasOwnProperty('type')) {
                obj['type'] = ApiClient.convertToType(data['type'], Object);
            }
            if (data.hasOwnProperty('max_fee')) {
                obj['max_fee'] = ApiClient.convertToType(data['max_fee'], ['Number']);
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
            if (data.hasOwnProperty('recipient')) {
                obj['recipient'] = ApiClient.convertToType(data['recipient'], Object);
            }
            if (data.hasOwnProperty('mosaics')) {
                obj['mosaics'] = ApiClient.convertToType(data['mosaics'], [MosaicDTO]);
            }
            if (data.hasOwnProperty('message')) {
                obj['message'] = MessageDTO.constructFromObject(data['message']);
            }
        }
        return obj;
    }


}

/**
 * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
 * @member {String} signature
 */
TransferTransactionDTO.prototype['signature'] = undefined;

/**
 * The public key of the entity signer formatted as hexadecimal.
 * @member {String} signer
 */
TransferTransactionDTO.prototype['signer'] = undefined;

/**
 * The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
 * @member {Number} version
 */
TransferTransactionDTO.prototype['version'] = undefined;

/**
 * @member {Object} type
 */
TransferTransactionDTO.prototype['type'] = undefined;

/**
 * @member {Array.<Number>} max_fee
 */
TransferTransactionDTO.prototype['max_fee'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
TransferTransactionDTO.prototype['deadline'] = undefined;

/**
 * If the bit 0 of byte 0 is not set (like in 0x90), then it is a regular address. Else (e.g. 0x91) it represents a namespace id which starts at byte 1.
 * @member {Object} recipient
 */
TransferTransactionDTO.prototype['recipient'] = undefined;

/**
 * The array of mosics sent to the recipient. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of a instead of a mosaicId corresponds to a mosaicId.
 * @member {Array.<module:model/MosaicDTO>} mosaics
 */
TransferTransactionDTO.prototype['mosaics'] = undefined;

/**
 * @member {module:model/MessageDTO} message
 */
TransferTransactionDTO.prototype['message'] = undefined;


// Implement TransactionDTO interface:
// Implement TransferTransactionBodyDTO interface:
/**
 * @member {Object} type
 */
TransferTransactionBodyDTO.prototype['type'] = undefined;
/**
 * If the bit 0 of byte 0 is not set (like in 0x90), then it is a regular address. Else (e.g. 0x91) it represents a namespace id which starts at byte 1.
 * @member {Object} recipient
 */
TransferTransactionBodyDTO.prototype['recipient'] = undefined;
/**
 * The array of mosics sent to the recipient. If the most significant bit of byte 0 is set, a namespaceId (alias) is used instead of a instead of a mosaicId corresponds to a mosaicId.
 * @member {Array.<module:model/MosaicDTO>} mosaics
 */
TransferTransactionBodyDTO.prototype['mosaics'] = undefined;
/**
 * @member {module:model/MessageDTO} message
 */
TransferTransactionBodyDTO.prototype['message'] = undefined;




export default TransferTransactionDTO;

