/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
 * The TransactionIds model module.
 * @module model/TransactionIds
 * @version 0.7.15
 */
class TransactionIds {
    /**
     * Constructs a new <code>TransactionIds</code>.
     * @alias module:model/TransactionIds
     */
    constructor() { 
        
        TransactionIds.initialize(this);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj) { 
    }

    /**
     * Constructs a <code>TransactionIds</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionIds} obj Optional instance to populate.
     * @return {module:model/TransactionIds} The populated <code>TransactionIds</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionIds();

            if (data.hasOwnProperty('transactionIds')) {
                obj['transactionIds'] = ApiClient.convertToType(data['transactionIds'], ['String']);
            }
        }
        return obj;
    }


}

/**
 * The array of transaction ids.
 * @member {Array.<String>} transactionIds
 */
TransactionIds.prototype['transactionIds'] = undefined;






export default TransactionIds;

