/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */

import ApiClient from '../ApiClient';

/**
* The TransactionStatusDTO model module.
* @module model/TransactionStatusDTO
* @version 0.7.15
*/
export default class TransactionStatusDTO {
    /**
     * Constructs a new <code>TransactionStatusDTO</code>.
     * @alias module:model/TransactionStatusDTO
     * @param status {String} 
     */
    constructor(status) { 
        
        TransactionStatusDTO.initialize(this, status);
    }

    /**
     * Initializes the fields of this object.
     * This method is used by the constructors of any subclasses, in order to implement multiple inheritance (mix-ins).
     * Only for internal use.
     */
    static initialize(obj, status) { 
        obj['status'] = status;
    }

    /**
     * Constructs a <code>TransactionStatusDTO</code> from a plain JavaScript object, optionally creating a new instance.
     * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
     * @param {Object} data The plain JavaScript object bearing properties of interest.
     * @param {module:model/TransactionStatusDTO} obj Optional instance to populate.
     * @return {module:model/TransactionStatusDTO} The populated <code>TransactionStatusDTO</code> instance.
     */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new TransactionStatusDTO();

            if (data.hasOwnProperty('group')) {
                obj['group'] = ApiClient.convertToType(data['group'], 'String');
            }
            if (data.hasOwnProperty('status')) {
                obj['status'] = ApiClient.convertToType(data['status'], 'String');
            }
            if (data.hasOwnProperty('hash')) {
                obj['hash'] = ApiClient.convertToType(data['hash'], 'String');
            }
            if (data.hasOwnProperty('deadline')) {
                obj['deadline'] = ApiClient.convertToType(data['deadline'], ['Number']);
            }
            if (data.hasOwnProperty('height')) {
                obj['height'] = ApiClient.convertToType(data['height'], ['Number']);
            }
        }
        return obj;
    }


}

/**
 * @member {String} group
 */
TransactionStatusDTO.prototype['group'] = undefined;

/**
 * @member {String} status
 */
TransactionStatusDTO.prototype['status'] = undefined;

/**
 * @member {String} hash
 */
TransactionStatusDTO.prototype['hash'] = undefined;

/**
 * @member {Array.<Number>} deadline
 */
TransactionStatusDTO.prototype['deadline'] = undefined;

/**
 * @member {Array.<Number>} height
 */
TransactionStatusDTO.prototype['height'] = undefined;






export default TransactionStatusDTO;

