/**
 * Catapult REST API Reference
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 */


import ApiClient from '../ApiClient';





/**
* The VerifiableEntityDTO model module.
* @module model/VerifiableEntityDTO
* @version 0.7.15
*/
export default class VerifiableEntityDTO {
    /**
    * Constructs a new <code>VerifiableEntityDTO</code>.
    * @alias module:model/VerifiableEntityDTO
    * @class
    * @param signature {String} The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    */

    constructor(signature) {
        



        this['signature'] = signature;

        
    }

    /**
    * Constructs a <code>VerifiableEntityDTO</code> from a plain JavaScript object, optionally creating a new instance.
    * Copies all relevant properties from <code>data</code> to <code>obj</code> if supplied or a new instance if not.
    * @param {Object} data The plain JavaScript object bearing properties of interest.
    * @param {module:model/VerifiableEntityDTO} obj Optional instance to populate.
    * @return {module:model/VerifiableEntityDTO} The populated <code>VerifiableEntityDTO</code> instance.
    */
    static constructFromObject(data, obj) {
        if (data) {
            obj = obj || new VerifiableEntityDTO();

            
            
            

            if (data.hasOwnProperty('signature')) {
                obj['signature'] = ApiClient.convertToType(data['signature'], 'String');
            }
        }
        return obj;
    }

    /**
    * The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    * @member {String} signature
    */
    signature = undefined;








}


