/**
 * Catapult REST API Reference
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * OpenAPI spec version: 0.7.15
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 *
 */


import ApiClient from "../ApiClient";
import NetworkTypeDTO from '../model/NetworkTypeDTO';

/**
* NetworkRoutes service.
* @module api/NetworkRoutesApi
* @version 0.7.15
*/
export default class NetworkRoutesApi {

    /**
    * Constructs a new NetworkRoutesApi. 
    * @alias module:api/NetworkRoutesApi
    * @class
    * @param {module:ApiClient} [apiClient] Optional API client implementation to use,
    * default to {@link module:ApiClient#instance} if unspecified.
    */
    constructor(apiClient) {
        this.apiClient = apiClient || ApiClient.instance;
    }



    /**
     * Get the current network type of the chain
     * Returns the current network type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with an object containing data of type {@link module:model/NetworkTypeDTO} and HTTP response
     */
    getNetworkTypeWithHttpInfo() {
      let postBody = null;

      let pathParams = {
      };
      let queryParams = {
      };
      let headerParams = {
      };
      let formParams = {
      };

      let authNames = [];
      let contentTypes = [];
      let accepts = ['application/json'];
      let returnType = NetworkTypeDTO;
      return this.apiClient.callApi(
        '/network', 'GET',
        pathParams, queryParams, headerParams, formParams, postBody,
        authNames, contentTypes, accepts, returnType, null
      );
    }

    /**
     * Get the current network type of the chain
     * Returns the current network type.
     * @return {Promise} a {@link https://www.promisejs.org/|Promise}, with data of type {@link module:model/NetworkTypeDTO}
     */
    getNetworkType() {
      return this.getNetworkTypeWithHttpInfo()
        .then(function(response_and_data) {
          return response_and_data.data;
        });
    }


}
